In [8]:
#Import your libraries here
# from pytickersymbols import PyTickerSymbols
from edgar import *
import nest_asyncio
nest_asyncio.apply()
import glob
import os
import pandas as pd
from tqdm import tqdm
import requests
from io import StringIO
import duckdb

In [2]:
pd.set_option("display.max_rows", 400)
pd.set_option("display.max_colwidth", 120)

In [3]:
# stock_data = PyTickerSymbols()

# # Expanded list to capture Small, Mid, and Large Cap companies
# indices = [
#     # --- USA (~4,500+ active tickers) ---
#     "S&P 500",            # Large Cap
#     "S&P 400",            # Mid Cap
#     "S&P 600",            # Small Cap
#     "RUSSELL 1000",       # Top 1000
#     "RUSSELL 2000",       # Small Cap Benchmark (Crucial for High Risk/Speculative)
#     "NASDAQ COMPOSITE",   # Virtually all Nasdaq listed stocks

#     # --- CANADA (~3,500+ active tickers) ---
#     "S&P TSX 60",         # Blue Chip
#     "S&P TSX COMPOSITE",  # The broad Canadian market
#     "S&P TSX VENTURE",    # High-risk, small-cap (Great for your "High Risk" bucket)

#     # --- EUROPE (~5,000+ active tickers) ---
#     "FTSE ALL-SHARE",     # UK Broad Market (Much larger than FTSE 100)
#     "SDAX",               # German Small Cap
#     "MDAX",               # German Mid Cap
#     "CAC ALL-SHARES",     # Broad French Market
#     "SPI",                # Swiss Performance Index (Nearly all Swiss stocks)
#     "STOXX EUROPE 600",   # Major companies across 17 European countries
#     "IBEX MEDIUM CAP",    # Spain
#     "BEL 20",             # Belgium
#     "AEX",                # Netherlands
#     "OMX STOCKHOLM 30",   # Sweden
#     "OMX COPENHAGEN 20"   # Denmark
# ]

# master_list = []
# for index in indices:
#     stocks = stock_data.get_stocks_by_index(index)
#     for s in stocks:
#         # Extract the Yahoo-compatible symbol
#         yahoo_symbol = s.get('symbol') 
#         master_list.append(yahoo_symbol)

# print(f"Collected {len(set(master_list))} unique tickers.")

In [4]:
# import nest_asyncio
# nest_asyncio.apply()

# from edgar import *

# # 1. Set your identity (Required by SEC)
# set_identity("Kamen Dimitrov kamendd@hotmail.com")

# # 2. Enable local storage and download the reference dataset
# # This downloads mapping files for all CIKs, tickers, and exchanges.
# download_edgar_data(reference=True)

# # 3. Access the full ticker mapping
# # This returns a pandas-compatible object of the SEC's master ticker list
# all_tickers = get_tickers() 
# print(f"Total Tickers Found: {len(all_tickers)}")

In [5]:
# from edgar import *

# use_local_storage(True)

# try:
#     tickers = get_company_tickers()
#     df_tickers = tickers.to_pandas() if hasattr(tickers, "to_pandas") else tickers

#     print("✅ Success! Local database connected.")
#     print(f"📊 Total Tickers: {len(df_tickers)}")
#     print(df_tickers.head())

# except Exception as e:
#     print(f"❌ Error: {e}")

In [6]:
# print(df_tickers.columns)

In [7]:
# from edgar import Company

# for t in ['A', 'WMT', 'JPM']:
#     try:
#         c = Company(t)
#         facts = c.get_facts()

#         assets = facts.get_total_assets()

#         print(f"Ticker: {t:4} | SIC: {c.sic} | Assets: ${assets:,.0f}")

#     except Exception as e:
#         print(f"❌ Error for {t}: {e}")

In [8]:
# df_tickers = df_tickers[df_tickers["ticker"].notna()]
# df_tickers

In [9]:
# use_local_storage(True)

# df = get_company_tickers()

# output_file = "fundamental_universe.csv"

# # Resume if file already exists
# if os.path.exists(output_file):
#     final_df = pd.read_csv(output_file)
#     completed = set(final_df["ticker"].tolist())
#     print(f"Resuming... already completed: {len(completed)}")
# else:
#     final_df = pd.DataFrame()
#     completed = set()

# rows = []

# for ticker in tqdm(df["ticker"].tolist()):
#     if ticker in completed:
#         continue

#     try:
#         c = Company(ticker)
#         facts = c.get_facts()

#         rows.append({
#             "ticker": ticker,
#             "cik": c.cik,
#             "name": c.name,
#             "sic": c.sic,
#             "sic_description": getattr(c, "sic_description", None),
#             "total_assets": facts.get_total_assets(),
#             "total_liabilities": facts.get_total_liabilities(),
#             "revenue": facts.get_revenue(),
#             "net_income": facts.get_net_income(),
#         })

#         # Save every 100 rows
#         if len(rows) >= 100:
#             temp_df = pd.DataFrame(rows)
#             final_df = pd.concat([final_df, temp_df], ignore_index=True)
#             final_df.to_csv(output_file, index=False)
#             rows = []

#     except Exception:
#         continue

# # Final save
# if rows:
#     temp_df = pd.DataFrame(rows)
#     final_df = pd.concat([final_df, temp_df], ignore_index=True)
#     final_df.to_csv(output_file, index=False)

# print("Done.")
# print(f"Total saved: {len(final_df)}")

In [10]:
# url = "https://www.sec.gov/corpfin/division-of-corporation-finance-standard-industrial-classification-sic-code-list"

# headers = {
#     "User-Agent": "your_email@domain.com",  # SEC likes this
#     "Accept-Language": "en-US,en;q=0.9",
#     "Accept-Encoding": "gzip, deflate, br",
#     "Host": "www.sec.gov"
# }

# response = requests.get(url, headers=headers)

# print(response.status_code)

# html_io = StringIO(response.text)

# tables = pd.read_html(html_io)

200

In [17]:
# sic_df = tables[0]
# sic_df = sic_df.rename(columns = {'SIC Code': 'sic'})
# sic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 444 entries, 0 to 443
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sic             444 non-null    int64
 1   Office          444 non-null    object
 2   Industry Title  444 non-null    object
dtypes: int64(1), object(2)
memory usage: 10.5+ KB

In [24]:
# fundamental_df = pd.read_csv("fundamental_universe.csv")

In [25]:
# fundamental_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9055 entries, 0 to 9054
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ticker             9054 non-null   object
 1   cik                9055 non-null   int64
 2   name               9055 non-null   object
 3   sic                8947 non-null   float64
 4   sic_description    0 non-null      float64
 5   total_assets       8992 non-null   float64
 6   total_liabilities  8903 non-null   float64
 7   revenue            7082 non-null   float64
 8   net_income         9005 non-null   float64
dtypes: float64(6), int64(1), object(2)
memory usage: 636.8+ KB

In [26]:
# fundamental_df = fundamental_df.dropna(subset=['sic', 'ticker'])
# fundamental_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8946 entries, 0 to 9054
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ticker             8946 non-null   object
 1   cik                8946 non-null   int64
 2   name               8946 non-null   object
 3   sic                8946 non-null   float64
 4   sic_description    0 non-null      float64
 5   total_assets       8900 non-null   float64
 6   total_liabilities  8811 non-null   float64
 7   revenue            7077 non-null   float64
 8   net_income         8913 non-null   float64
dtypes: float64(6), int64(1), object(2)
memory usage: 698.9+ KB

In [27]:
# fundamental_df = fundamental_df.merge(
#     sic_df,
#     how='left',
#     on='sic'
# )

In [28]:
# fundamental_df = fundamental_df.drop(columns=["sic_description"])
# fundamental_df

,ticker,cik,name,sic,total_assets,total_liabilities,revenue,net_income,Office,Industry Title
0,A,1090872,"AGILENT TECHNOLOGIES, INC.",3826.0,1.272700e+10,5.986000e+09,6.948000e+09,1.303000e+09,Industrial Applications and Services,LABORATORY ANALYTICAL INSTRUMENTS
1,AA,1675149,Alcoa Corp,3334.0,1.612900e+10,9.935000e+09,1.283100e+10,1.157000e+09,Office of Manufacturing,PRIMARY PRODUCTION OF ALUMINUM
2,AAAU,1708646,Goldman Sachs Physical Gold ETF,6221.0,2.542910e+09,3.809370e+05,NaN,7.834461e+08,Office of Crypto Assets,COMMODITY CONTRACTS BROKERS & DEALERS
3,AACB,2034334,Artius II Acquisition Inc.,6770.0,2.282833e+08,1.399455e+07,NaN,1.362370e+05,Office of Real Estate & Construction,BLANK CHECKS
4,AACBR,2034334,Artius II Acquisition Inc.,6770.0,2.282833e+08,1.399455e+07,NaN,1.362370e+05,Office of Real Estate & Construction,BLANK CHECKS
...,...,...,...,...,...,...,...,...,...,...
8941,ZVSA,1859007,"ZyVersa Therapeutics, Inc.",2834.0,3.479010e+05,1.273469e+07,NaN,-2.495238e+07,Office of Life Sciences,PHARMACEUTICAL PREPARATIONS
8942,ZWS,1439288,Zurn Elkay Water Solutions Corp,3560.0,2.679400e+09,1.076100e+09,1.695900e+09,1.980000e+08,Office of Technology,GENERAL INDUSTRIAL MACHINERY & EQUIPMENT
8943,ZYBT,1975641,Zhengye Biotechnology Holding Ltd,2834.0,4.932470e+08,1.407070e+08,1.863560e+08,1.131100e+07,Office of Life Sciences,PHARMACEUTICAL PREPARATIONS
8944,ZYME,1937653,Zymeworks Inc.,2834.0,3.465270e+08,7.802600e+07,1.059650e+08,-8.113000e+07,Office of Life Sciences,PHARMACEUTICAL PREPARATIONS
8945,ZYXIQ,846475,ZYNEX INC,3845.0,1.220790e+08,8.637100e+07,2.343200e+07,2.994000e+06,Industrial Applications and Services,ELECTROMEDICAL & ELECTROTHERAPEUTIC APPARATUS

In [29]:
# fundamental_df.to_csv("fundamental_universe_ticker_cik_sic.csv")

In [30]:
fundamental_df = pd.read_csv("fundamental_universe_ticker_cik_sic.csv")
fundamental_df

,Unnamed: 0,ticker,cik,name,sic,total_assets,total_liabilities,revenue,net_income,Office,Industry Title
0,0,A,1090872,"AGILENT TECHNOLOGIES, INC.",3826.0,1.272700e+10,5.986000e+09,6.948000e+09,1.303000e+09,Industrial Applications and Services,LABORATORY ANALYTICAL INSTRUMENTS
1,1,AA,1675149,Alcoa Corp,3334.0,1.612900e+10,9.935000e+09,1.283100e+10,1.157000e+09,Office of Manufacturing,PRIMARY PRODUCTION OF ALUMINUM
2,2,AAAU,1708646,Goldman Sachs Physical Gold ETF,6221.0,2.542910e+09,3.809370e+05,NaN,7.834461e+08,Office of Crypto Assets,COMMODITY CONTRACTS BROKERS & DEALERS
3,3,AACB,2034334,Artius II Acquisition Inc.,6770.0,2.282833e+08,1.399455e+07,NaN,1.362370e+05,Office of Real Estate & Construction,BLANK CHECKS
4,4,AACBR,2034334,Artius II Acquisition Inc.,6770.0,2.282833e+08,1.399455e+07,NaN,1.362370e+05,Office of Real Estate & Construction,BLANK CHECKS
...,...,...,...,...,...,...,...,...,...,...,...
8941,8941,ZVSA,1859007,"ZyVersa Therapeutics, Inc.",2834.0,3.479010e+05,1.273469e+07,NaN,-2.495238e+07,Office of Life Sciences,PHARMACEUTICAL PREPARATIONS
8942,8942,ZWS,1439288,Zurn Elkay Water Solutions Corp,3560.0,2.679400e+09,1.076100e+09,1.695900e+09,1.980000e+08,Office of Technology,GENERAL INDUSTRIAL MACHINERY & EQUIPMENT
8943,8943,ZYBT,1975641,Zhengye Biotechnology Holding Ltd,2834.0,4.932470e+08,1.407070e+08,1.863560e+08,1.131100e+07,Office of Life Sciences,PHARMACEUTICAL PREPARATIONS
8944,8944,ZYME,1937653,Zymeworks Inc.,2834.0,3.465270e+08,7.802600e+07,1.059650e+08,-8.113000e+07,Office of Life Sciences,PHARMACEUTICAL PREPARATIONS
8945,8945,ZYXIQ,846475,ZYNEX INC,3845.0,1.220790e+08,8.637100e+07,2.343200e+07,2.994000e+06,Industrial Applications and Services,ELECTROMEDICAL & ELECTROTHERAPEUTIC APPARATUS

In [23]:
fundamental_df["sic"].value_counts()

sic
6770.0    727
2834.0    692
6798.0    389
7372.0    335
6022.0    240
         ...
2531.0      1
5063.0      1
3086.0      1
3715.0      1
3452.0      1
Name: count, Length: 398, dtype: int64

In [31]:
fundamental_df["Industry Title"].value_counts()

Industry Title
BLANK CHECKS                                                   727
PHARMACEUTICAL PREPARATIONS                                    692
REAL ESTATE INVESTMENT TRUSTS                                  389
SERVICES-PREPACKAGED SOFTWARE                                  335
STATE COMMERCIAL BANKS                                         240
                                                              ...
PUBLIC BLDG & RELATED FURNITURE                                  1
WHOLESALE-ELECTRICAL APPARATUS & EQUIPMENT, WIRING SUPPLIES      1
PLASTICS FOAM PRODUCTS                                           1
TRUCK TRAILERS                                                   1
BOLTS, NUTS, SCREWS, RIVETS & WASHERS                            1
Name: count, Length: 398, dtype: int64

In [34]:
sic_audit = (
    fundamental_df
    .groupby(["sic", "Industry Title"])
    .agg(
        company_count=("ticker", "count"),
        sample_tickers=("ticker", lambda x: ", ".join(x.astype(str).head(10))),
        sample_names=("name", lambda x: " | ".join(x.astype(str).head(5)))
    )
    .reset_index()
    .sort_values("company_count", ascending=False)
)

sic_audit

,sic,Industry Title,company_count,sample_tickers,sample_names
337,6770.0,BLANK CHECKS,727,"AACB, AACBR, AACBU, AACI, AACIU, AACIU, AACO, AACOU, AAM, ACQC",Artius II Acquisition Inc. | Artius II Acquisition Inc. | Artius II Acquisition Inc. | Armada Acquisition Corp. III ...
77,2834.0,PHARMACEUTICAL PREPARATIONS,692,"AAPG, AARD, AAVXF, ABBV, ABCL, ABEO, ABT, ABUS, ABVC, ABVX","ASCENTAGE PHARMA GROUP INTERNATIONAL | Aardvark Therapeutics, Inc. | Abivax S.A. | AbbVie Inc. | AbCellera Biologics..."
341,6798.0,REAL ESTATE INVESTMENT TRUSTS,389,"AAT, ABR, ABR-PD, ABR-PE, ABR-PF, ACR, ACR-PC, ACR-PD, ACRE, ADAM","American Assets Trust, Inc. | ARBOR REALTY TRUST INC | ARBOR REALTY TRUST INC | ARBOR REALTY TRUST INC | ARBOR REALT..."
358,7372.0,SERVICES-PREPACKAGED SOFTWARE,335,"ACIW, ADAD, ADBE, ADSK, AEYE, AI, AIFF, AISP, AISPW, AITX","ACI WORLDWIDE, INC. | Huaizhong Health Group, Inc. | ADOBE INC. | Autodesk, Inc. | AUDIOEYE INC"
306,6022.0,STATE COMMERCIAL BANKS,240,"ABCB, ACNB, ADZCF, ALLY, AMAL, ASB, ASB-PE, ASB-PF, ASBA, AUB",Ameris Bancorp | ACNB CORP | DEUTSCHE BANK AKTIENGESELLSCHAFT | Ally Financial Inc. | Amalgamated Financial Corp.
79,2836.0,"BIOLOGICAL PRODUCTS, (NO DISGNOSTIC SUBSTANCES)",212,"ABOS, ABP, ABPO, ABPWW, ACLX, ACOG, ADMA, ADPT, ADVM, AGEN","Acumen Pharmaceuticals, Inc. | Abpro Holdings, Inc. | Abpro Holdings, Inc. | Abpro Holdings, Inc. | Arcellx, Inc."
305,6021.0,NATIONAL COMMERCIAL BANKS,206,"ALRS, AMJB, AMTB, AMUB, AROW, ASRV, ATLO, BAC, BAC-PB, BAC-PE",ALERUS FINANCIAL CORP | JPMORGAN CHASE & CO | Amerant Bancorp Inc. | UBS AG | ARROW FINANCIAL CORP
317,6199.0,FINANCE SERVICES,188,"ABIT, ABTC, ABTS, AIXC, AMBR, AMTD, ANY, ARBK, ARBKF, ASST","Athena Bitcoin Global | American Bitcoin Corp. | Abits Group Inc | AIxCrypto Holdings, Inc. | Amber International Ho..."
201,3841.0,SURGICAL & MEDICAL INSTRUMENTS & APPARATUS,180,"ADGM, AEMD, ALUR, ALUR-WT, AMIX, ANGO, ANIK, AORT, APYX, ARAY","Adagio Medical Holdings, Inc. | AETHLON MEDICAL INC | ALLURION TECHNOLOGIES, INC. | ALLURION TECHNOLOGIES, INC. | Au..."
364,7389.0,"SERVICES-BUSINESS SERVICES, NEC",167,"ACN, ACVA, ADV, AHG, AKAM, ALIT, AMTM, AMWL, ANDG, ASFH",Accenture plc | ACV Auctions Inc. | Advantage Solutions Inc. | Akso Health Group | AKAMAI TECHNOLOGIES INC
9,1311.0,CRUDE PETROLEUM & NATURAL GAS,130,"AESI, AGIG, ALTX, AMIH, AMPY, ANNA, ANNAW, APA, APHD, AR","Atlas Energy Solutions Inc. | ABUNDIA GLOBAL IMPACT GROUP, INC. | ALTEX INDUSTRIES INC | AMERICAN INTERNATIONAL HOLD..."
320,6221.0,COMMODITY CONTRACTS BROKERS & DEALERS,123,"AAAU, AGQ, AIB, ALTS, ANTA, ARKB, BAR, BCHG, BDRY, BITB","Goldman Sachs Physical Gold ETF | ProShares Trust II | BlockchAIn Digital Infrastructure, Inc. | ALT5 Sigma Corp | A..."
173,3674.0,SEMICONDUCTORS & RELATED DEVICES,118,"AAOI, ADI, ADTTF, AIP, ALAB, ALGM, ALMU, AMAT, AMBA, AMBQ","APPLIED OPTOELECTRONICS, INC. | ANALOG DEVICES INC | ADVANTEST CORP | Arteris, Inc. | Astera Labs, Inc."
360,7374.0,SERVICES-COMPUTER PROCESSING & DATA PREPARATION,117,"ADP, AIAI, APLD, ATHM, AUUD, AUUDW, AVAI, BHIC, BILI, BLBLF",AUTOMATIC DATA PROCESSING INC | AIAI Holdings Corp | Applied Digital Corp. | Autohome Inc. | AUDDIA INC.
237,4911.0,ELECTRIC SERVICES,116,"AEP, AGQPF, APSI, AQN, AQNB, ASRE, AXIA, AXIA-P, AXIA-PC, BEP",AMERICAN ELECTRIC POWER CO INC | ALGONQUIN POWER & UTILITIES CORP. | AQUA POWER SYSTEMS INC. | ALGONQUIN POWER & UTI...
356,7370.0,"SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING, ETC.",113,"AIJTY, ALYAF, APP, BAIDF, BBLR, BIDU, BLND, BMBL, BRGX, BZ","Jianpu Technology Inc. | Alithya Group inc | AppLovin Corp | Baidu, Inc. | Bubblr Inc."
5,1040.0,GOLD AND SILVER ORES,113,"AEM, AG, AGI, AHNRF, ARAO, ARIS, ARMN, ATCX, AU, AUMN","AGNICO EAGLE MINES LTD | FIRST MAJESTIC SILVER CORP | ALAMOS GOLD INC | ATHENA GOLD CORP | AuraSource, Inc."
4,1000.0,METAL MINING,94,"AAUAF, ACRL, ADMG, AEC, ALM, ALOY, AMLIF, AMLM, ARRKF, ARRT","ALMADEN MINERALS LTD | Atacama Resources International, Inc. | ADAMANT DRI PROCESSING & MINERALS GROUP | ANFIELD ENE..."
325,6331.0,"FIRE, MARINE & CASUALTY INSURANCE",93,"ACGL, ACGLN, ACGLO, ACIC, AFG, AFGB, AFGC, AFGD, AFGE, AHL",ARCH CAPITAL GROUP LTD. | ARCH CAPITAL GROUP LTD. | ARCH CAPITAL GROUP LTD. | AMERICAN COASTAL INSURANCE Corp | AMER...
307,6029.0,"COMMERCIAL BANKS, NEC",81,"ATMP, AVAL, BAP, BBAR, BBVA, BBVXF, BCDRF, BCH, BCLYF, BCS",BARCLAYS BANK PLC | Grupo Aval Acciones Y Valores S.A. | CREDICORP LTD | Banco BBVA Argentina S.A. | BANCO BILBAO VI...
321,6282.0,INVESTMENT ADVICE,80,"AAMI, AB, ABX, ABXL, ALTI, AMG, AMP, APAM, APO, APO-PA","Acadian Asset Management Inc. | ALLIANCEBERNSTEIN HOLDING L.P. | Abacus Global Management, Inc. | Abacus Global Mana..."
177,3690.0,"MISCELLANEOUS ELECTRICAL MACHINERY, EQUIPMENT & SUPPLIES",76,"ADNH, ADNWW, ADSE, ADSEW, AMPX, AMPX-WT, ATKR, AUSI, BEEM, BLNK","ADVENT TECHNOLOGIES HOLDINGS, INC. | ADVENT TECHNOLOGIES HOLDINGS, INC. | Ads-Tec Energy Public Ltd Co | Ads-Tec Ene..."
359,7373.0,SERVICES-COMPUTER INTEGRATED SYSTEMS DESIGN,75,"AGYS, ARBB, ARBE, ARBEW, ASUR, AUR, AUROW, BACQ, BACQR, BACQU",AGILYSYS INC | ARB IOT Group Ltd | Arbe Robotics Ltd. | Arbe Robotics Ltd. | ASURE SOFTWARE INC
330,6500.0,REAL ESTATE,72,"AEI, AHH, AHH-PA, AHRT, AHRT-PA, AIRE, AOMD, AOMN, AOMR, AOXY","Alset Inc. | AH Realty Trust, Inc. | AH Realty Trust, Inc. | AH Realty Trust, Inc. | AH Realty Trust, Inc."
357,7371.0,SERVICES-COMPUTER PROGRAMMING SERVICES,69,"AGMH, ALBT, ANKM, APYP, ATGL, BMTM, BTTC, CINT, CTSH, CYCU","AGM GROUP HOLDINGS, INC. | Avalon GloboCare Corp. | Ankam, Inc. | APPYEA, INC | Alpha Technology Group Ltd"
388,8200.0,SERVICES-EDUCATIONAL SERVICES,63,"AACG, ACATD, AFYA, AMBO, APEI, ASPU, ATGE, BOXL, BRWC, BSAA",ATA Creativity Global | NP Life Sciences Health Industry Group Inc. | Afya Ltd | Ambow Education Holding Ltd. | AMER...
395,8742.0,SERVICES-MANAGEMENT CONSULTING SERVICES,62,"ACCL, ACCS, AERT, AERTW, AGLY, ALEH, ASTH, BAH, BDTB, BLNC","Acco Group Holdings Ltd | ACCESS Newswire Inc. | Aeries Technology, Inc. | Aeries Technology, Inc. | Atlantis Glory ..."
319,6211.0,"SECURITY BROKERS, DEALERS & FLOTATION COMPANIES",59,"ACGP, AXG, BLK, BULL, BULLW, COHN, DOMH, ETOR, FRHC, FUTU","Associated Capital Group, Inc. | Solowin Holdings, Ltd. | BlackRock, Inc. | Webull Corp | Webull Corp"
296,5812.0,RETAIL-EATING PLACES,59,"ARCO, ARKR, ARMK, BABB, BDL, BH, BH-A, BJRI, BLMN, BTBD","Arcos Dorados Holdings Inc. | ARK RESTAURANTS CORP | Aramark | BAB, INC. | FLANIGANS ENTERPRISES INC"
221,4412.0,DEEP SEA FOREIGN TRANSPORTATION OF FREIGHT,58,"ASC, CCEC, CDLR, CISS, CMBT, CMRE, CMRE-PB, CMRE-PC, CMRE-PD, CTRM",Ardmore Shipping Corp | Capital Clean Energy Carriers Corp. | Cadeler A/S | C3is Inc. | CMB.TECH NV
180,3714.0,MOTOR VEHICLE PARTS & ACCESSORIES,56,"ADNT, AEAE, AEAEU, AEAEW, AEVA, AEVAW, ALSN, ALV, APTV, ATMU",Adient plc | AltEnergy Acquisition Corp | AltEnergy Acquisition Corp | AltEnergy Acquisition Corp | Aeva Technologie...
322,6311.0,LIFE INSURANCE,56,"AAME, AEFC, AEG, AEGOF, ANG-PD, ATH-PA, ATH-PB, ATH-PD, ATH-PE, ATHS",ATLANTIC AMERICAN CORP | AEGON LTD. | AEGON LTD. | AEGON LTD. | American National Group Inc.
178,3711.0,MOTOR VEHICLES & PASSENGER CAR BODIES,55,"AIEV, AIIO, AIIOW, BINI, CENN, DCX, ECDA, ECDAW, EMPD, F","Thunder Power Holdings, Inc. | ROBO.AI INC. | ROBO.AI INC. | BOLLINGER INNOVATIONS, INC. | Cenntro Inc."
230,4813.0,TELEPHONE COMMUNICATIONS (NO RADIOTELEPHONE),55,"AMX, AMXOF, ATEX, ATNI, BCAEF, BCE, BCEFF, BCENF, BCEPF, BCEXF","AMERICA MOVIL SAB DE CV/ | AMERICA MOVIL SAB DE CV/ | Anterix Inc. | ATN International, Inc. | BCE INC"
76,2833.0,MEDICINAL CHEMICALS & BOTANICAL PRODUCTS,54,"AAWH, ABTI, ACB, ADIA, AIBT, AKAN, AMMJ, AYRWF, AYWWF, BON","Ascend Wellness Holdings, Inc. | ALTEROLA BIOTECH INC. | AURORA CANNABIS INC | Adia Nutrition, Inc. | AIBOTICS, INC."
308,6035.0,"SAVINGS INSTITUTION, FEDERALLY CHARTERED",49,"AX, BCBP, BCTF, BKU, BVFL, BYFC, CARV, CFFN, CFSB, CLBK","Axos Financial, Inc. | BCB BANCORP INC | Bancorp 34, Inc. | BankUnited, Inc. | BV Financial, Inc."
311,6111.0,FEDERAL & FEDERALLY-SPONSORED CREDIT AGENCIES,48,"AGM, AGM-A, AGM-PD, AGM-PE, AGM-PF, AGM-PG, AGM-PH, FMCC, FMCCG, FMCCH",FEDERAL AGRICULTURAL MORTGAGE CORP | FEDERAL AGRICULTURAL MORTGAGE CORP | FEDERAL AGRICULTURAL MORTGAGE CORP | FEDER...
373,7900.0,SERVICES-AMUSEMENT & RECREATION SERVICES,45,"ACBM, ACEL, ADTI, AFOM, AGAE, APHP, BATRA, BATRB, BATRK, BOTY","ACRO BIOMEDICAL CO., LTD. | Accel Entertainment, Inc. | Adapti, Inc. | ALL FOR ONE MEDIA CORP. | Allied Gaming & Ent..."
303,5961.0,RETAIL-CATALOG & MAIL-ORDER HOUSES,41,"AKA, ALID, AMZE, AMZN, BBBY, BBBY-WT, BWMX, BZUN, CAHO, CDW","A.K.A. BRANDS HOLDING CORP. | Allied Corp. | AMAZE HOLDINGS, INC. | AMAZON COM INC | BED BATH & BEYOND, INC."
202,3842.0,"ORTHOPEDIC, PROSTHETIC & SURGICAL APPLIANCES & SUPPLIES",41,"AGPU, ALGN, APT, AVNS, AVR, BBLG, BBLGW, BNKL, CDRE, CLGN","Axe Compute Inc. | ALIGN TECHNOLOGY INC | ALPHA PRO TECH LTD | AVANOS MEDICAL, INC. | Anteris Technologies Global Corp."
329,6411.0,"INSURANCE AGENTS, BROKERS & SERVICE",41,"AAPI, ACT, AIFU, AJG, AON, ARX, BRO, BWIN, CCG, CCGWW","Apple iSports Group, Inc. | Enact Holdings, Inc. | AIFU Inc. | Arthur J. Gallagher & Co. | Aon plc"
205,3845.0,ELECTROMEDICAL & ELECTROTHERAPEUTIC APPARATUS,41,"ADMT, AXGN, BLFS, CBLL, CNMD, CV, ECOR, EDAP, ELMD, ENDV","ADM TRONICS UNLIMITED, INC. | Axogen, Inc. | BIOLIFE SOLUTIONS INC | Ceribell, Inc. | CONMED Corp"
375,7990.0,SERVICES-MISCELLANEOUS AMUSEMENT & RECREATION,40,"APAD, APADR, APADU, BRSL, BRVO, BUKS, CDRO, CDROW, DIS, DKNG",AParadise Acquisition Corp. | AParadise Acquisition Corp. | AParadise Acquisition Corp. | Brightstar Lottery PLC | B...
241,4931.0,ELECTRIC & OTHER SERVICES COMBINED,39,"AEE, ALCE, ALE, AVA, CMS, CMS-PC, CMSA, CMSC, CMSD, DUK","AMEREN CORP | Alternus Clean Energy, Inc. | ALLETE INC | AVISTA CORP | CMS ENERGY CORP"
309,6036.0,"SAVINGS INSTITUTIONS, NOT FEDERALLY CHARTERED",38,"AFBI, AVBC, BBT, BCOW, BLFY, BSBK, CULL, ECBK, EWSB, FBLA","Affinity Bancshares, Inc. | Avidia Bancorp, Inc. | Beacon Financial Corp | 1895 Bancorp of Wisconsin, Inc. /MD/ | Bl..."
84,2860.0,INDUSTRIAL ORGANIC CHEMICALS,38,"ALTO, AMTX, BAK, BIOF, BSLK, BSLKW, CDXS, CLNV, CNEY, FF","Alto Ingredients, Inc. | AEMETIS, INC | BRASKEM SA | BLUE BIOFUELS, INC. | Bolt Projects Holdings, Inc."
238,4922.0,NATURAL GAS TRANSMISSION,38,"AM, AROC, DTM, EP-PC, EPD, EPDU, ET, ET-PI, KGS, KMI","Antero Midstream Corp | Archrock, Inc. | DT Midstream, Inc. | KINDER MORGAN, INC. | ENTERPRISE PRODUCTS PARTNERS L.P."
220,4400.0,WATER TRANSPORTATION,37,"BIP, BIP-PA, BIP-PB, BIPH, BIPI, BIPJ, BRIPF, CCL, CLCO, CMDB",Brookfield Infrastructure Partners L.P. | Brookfield Infrastructure Partners L.P. | Brookfield Infrastructure Partne...
235,4899.0,"COMMUNICATIONS SERVICES, NEC",36,"AEHL, AKOM, ANGH, ANGHW, ASTS, BZFD, BZFDW, CALX, CCOI, CLUS","Antelope Enterprise Holdings Ltd | Aerkomm Inc. | Anghami Inc | Anghami Inc | AST SpaceMobile, Inc."
383,8071.0,SERVICES-MEDICAL LABORATORIES,35,"ACON, ACONW, ADVB, AMS, BDSX, BGLC, BLLN, BNR, CAI, CDNA","Aclarion, Inc. | Aclarion, Inc. | Advanced Biomed Inc. | AMERICAN SHARED HOSPITAL SERVICES | BIODESIX INC"
169,3663.0,RADIO & TV BROADCASTING & COMMUNICATIONS EQUIPMENT,35,"AIRG, ANDR, AVNW, BDRL, BKSY, BKSY-WT, BKTI, CMBM, CMTL, CONC","AIRGAIN INC | ANDREA ELECTRONICS CORP | AVIAT NETWORKS, INC. | BLONDER TONGUE LABORATORIES INC | BlackSky Technology..."
33,2080.0,BEVERAGES,34,"ABEV, ASII, BF-A, BF-B, BRCC, BUDA, CIRX, COCO, CWGL, DEO","AMBEV S.A. | Accredited Solutions, Inc. | BROWN FORMAN CORP | BROWN FORMAN CORP | BRC Inc."
344,7011.0,HOTELS & MOTELS,34,"ATAT, BALY, BYD, CHH, CNTY, CZR, DHCC, FLL, GHG, H",Atour Lifestyle Holdings Ltd | Bally's Corp | BOYD GAMING CORP | CHOICE HOTELS INTERNATIONAL INC /DE | CENTURY CASIN...
0,100.0,AGRICULTURAL PRODUCTION-CROPS,34,"AGRO, AGRZ, ALCO, CBSTF, CTVA, CWBHF, DOLE, EDBL, EDBLW, ESGH","Adecoagro S.A. | Agroz Inc. | ALICO, INC. | Cannabist Co Holdings Inc. | Corteva, Inc."
13,1400.0,MINING & QUARRYING OF NONMETALLIC MINERALS (NO FUELS),33,"ABAT, ACRG, ATLX, BLTH, CMP, ELBM, ELVR, FEAM, FEAV, FRSPF","AMERICAN BATTERY TECHNOLOGY Co | American Clean Resources Group, Inc. | Atlas Lithium Corp | AMERICAN BATTERY MATERI..."
346,7310.0,SERVICES-ADVERTISING,32,"ADMQ, ANGI, BLIS, CAMG, CCO, CMGO, DRCT, EDHL, EZOO, FLNT","ADM ENDEAVORS, INC. | Angi Inc. | NAPC Defense, Inc. | CAM GROUP, INC. | Clear Channel Outdoor Holdings, Inc."
222,4512.0,"AIR TRANSPORTATION, SCHEDULED",31,"AAL, ALGT, ALK, AZLUD, AZSAQ, AZSAY, AZULQ, AZUXQ, AZUXY, CHEAF","American Airlines Group Inc. | Allegiant Travel CO | ALASKA AIR GROUP, INC. | AZUL SA | AZUL SA"
297,5900.0,RETAIL-MISCELLANEOUS RETAIL,31,"AASP, BLMH, BLPG, CIMG, DVLP, ESSI, EZPW, FCFS, FGPR, FGPRB","Agassi Sports Entertainment Corp. | BLUM HOLDINGS, INC. | Blue Line Protection Group, Inc. | CIMG Inc. | Golden Deve..."
21,2000.0,FOOD AND KINDRED PRODUCTS,30,"BGS, BOF, BRBF, BRBR, BRLS, BRLSW, BYND, CAG, CHSN, CPB","B&G Foods, Inc. | BranchOut Food Inc. | BRB Foods Inc. | BELLRING BRANDS, INC. | Borealis Foods Inc."
198,3826.0,LABORATORY ANALYTICAL INSTRUMENTS,29,"A, ASTC, AVTR, BFNH, BIO, BIO-B, BNGO, BRKR, BRKRP, CTKB","AGILENT TECHNOLOGIES, INC. | ASTROTECH Corp | Avantor, Inc. | BIOFORCE NANOSCIENCES HOLDINGS, INC. | BIO-RAD LABORAT..."
227,4700.0,TRANSPORTATION SERVICES,29,"BKNG, BWLP, CNNC, EXPE, GATX, GBTG, GXO, HAFN, LIND, MGSD","Booking Holdings Inc. | BW LPG Ltd | Cannonau Corp. | Expedia Group, Inc. | GATX CORP"
19,1700.0,CONSTRUCTION - SPECIAL TRADE CONTRACTORS,28,"ACPS, AGX, AMRC, BBCP, BBU, BBUC, BLD, CNTM, FGL, LGN","AC Partners, Inc. | ARGAN INC | Ameresco, Inc. | Concrete Pumping Holdings, Inc. | Brookfield Business Corp"
234,4841.0,CABLE & OTHER PAY TELEVISION SERVICES,28,"ADEA, AMCX, AREN, CABO, CCZ, CHTR, CMCSA, GLIBA, GLIBB, GLIBK","Adeia Inc. | AMC Global Media Inc. | Arena Group Holdings, Inc. | Cable One, Inc. | COMCAST CORP"
304,5990.0,"RETAIL-RETAIL STORES, NEC",26,"ALTB, BARK, BARKW, BBWI, BQ, FLWS, HITI, JD, JDCMF, LESL","Alpine Auto Brokers Inc. | Bark, Inc. | Bark, Inc. | Bath & Body Works, Inc. | Boqii Holding Ltd"
82,2844.0,"PERFUMES, COSMETICS & OTHER TOILET PREPARATIONS",26,"AXIL, BNKK, CABR, CL, COTY, CSCIF, DQWS, EL, ELF, EOSS","Axil Brands, Inc. | BONK, INC. | Caring Brands, Inc. | COLGATE PALMOLIVE CO | COTY INC."
355,7363.0,SERVICES-HELP SUPPLY SERVICES,26,"ALTD, AMN, ASGN, ATLN, BBSI, BGSF, CCRN, DHTI, DLHC, HQI","ALTITUDE INTERNATIONAL HOLDINGS, INC. | AMN HEALTHCARE SERVICES INC | Everforth Inc | ATLANTIC INTERNATIONAL CORP. |..."
15,1531.0,OPERATIVE BUILDERS,26,"BZH, CCS, DFH, DHI, DREM, ECG, GRBK, GRBK-PA, HOV, HOVNP","BEAZER HOMES USA INC | Century Communities, Inc. | Dream Finders Homes, Inc. | HORTON D R INC /DE/ | Dream Homes & D..."
377,8000.0,SERVICES-HEALTH SERVICES,26,"AONC, AONCW, ATPC, BTTX, DCGO, EUDA, EUDAW, INNV, LDDD, LFST","American Oncology Network, Inc. | American Oncology Network, Inc. | Agape ATP Corp | Better Therapeutics, Inc. | Doc..."
170,3669.0,"COMMUNICATIONS EQUIPMENT, NEC",26,"AIOT, ALPP, ALRTF, AMPG, AMPGR, AMPGW, AMPGZ, ASNS, COMS, CRTG","Powerfleet, Inc. | ALPINE 4 HOLDINGS, INC. | ALR Technologies SG Ltd. | AmpliTech Group, Inc. | AmpliTech Group, Inc."
285,5500.0,RETAIL-AUTO DEALERS & GASOLINE STATIONS,26,"ABG, AN, CASY, CPRT, CRMT, CSAN, CVNA, CWH, EVOA, GORV","ASBURY AUTOMOTIVE GROUP INC | AUTONATION, INC. | CASEYS GENERAL STORES INC | COPART INC | AMERICAS CARMART INC"
6,1090.0,MISCELLANEOUS METAL ORES,25,"AVPMF, CCJ, CNNA, DNN, ELRE, EU, FMST, FMSTW, FNUC, GLNS",AVRUPA MINERALS LTD. | CAMECO CORP | Cann American Corp. | DENISON MINES CORP. | Yinfu Gold Corp.
184,3721.0,AIRCRAFT,25,"ACHR, ACHR-WT, AIRO, AVAV, BA, BA-PA, BANT, BETA, DPRO, DUKR","Archer Aviation Inc. | Archer Aviation Inc. | AIRO Group Holdings, Inc. | AeroVironment Inc | BOEING CO"
226,4610.0,PIPE LINES (NO NATURAL GAS),25,"DINO, DKL, EBBGF, EBBNF, EBGEF, EBRGF, EBRZF, ENB, ENBFF, ENBGF","HF Sinclair Corp | Delek Logistics Partners, LP | ENBRIDGE INC | ENBRIDGE INC | ENBRIDGE INC"
335,6531.0,REAL ESTATE AGENTS & MANAGERS (FOR OTHERS),24,"BEKE, COMP, DOUG, EXPI, FTHM, GLEI, HOUS, JLL, LHAI, LRHC","KE Holdings Inc. | Compass, Inc. | Douglas Elliman Inc. | eXp World Holdings, Inc. | Fathom Holdings Inc."
12,1389.0,"OIL & GAS FIELD SERVICES, NEC",24,"ACDC, CLB, ENSV, GNOLF, HAL, HLX, KLXE, LBRT, NCSM, NESR",ProFrac Holding Corp. | Core Laboratories Inc. /DE/ | Enservco Corp | GENOIL INC | HALLIBURTON CO
229,4812.0,RADIOTELEPHONE COMMUNICATIONS,24,"AD, CHAI, CHT, CLRI, IHS, KYIV, KYIVW, MLCMF, PTNRF, SIDU","ARRAY DIGITAL INFRASTRUCTURE, INC. | Core AI Holdings, Inc. | CHUNGHWA TELECOM CO LTD | Cleartronic, Inc. | IHS Hold..."
332,6512.0,OPERATORS OF NONRESIDENTIAL BUILDINGS,23,"ABCP, AWCA, BAMGF, BAMKF, BKAMF, BKFAF, BKFDF, BKFOF, BKFPF, BKPA","AmBase Corp | Awaysis Capital, Inc. | BROOKFIELD Corp /ON/ | BROOKFIELD Corp /ON/ | BROOKFIELD Corp /ON/"
392,8731.0,SERVICES-COMMERCIAL PHYSICAL & BIOLOGICAL RESEARCH,22,"ABSI, BIAF, BIAFW, BUDZ, CBIH, CRL, FOXO, FOXOW, ICLR, INCY","Absci Corp | bioAffinity Technologies, Inc. | bioAffinity Technologies, Inc. | WEED, INC. | Cannabis Bioscience Inte..."
78,2835.0,IN VITRO & IN VIVO DIAGNOSTIC SUBSTANCES,22,"ACHV, AWHL, BMRA, BZYR, CDIO, CDIOW, CLDX, ICCC, IDXX, IMDX","ACHIEVE LIFE SCIENCES, INC. | Aspira Women's Health Inc. | BIOMERICA INC | BURZYNSKI RESEARCH INSTITUTE INC | Cardio..."
88,2911.0,PETROLEUM REFINING,22,"BP, BPAQF, BPPFF, CLMT, COP, CVI, CVX, DK, EQNR, IEP","BP PLC | BP PLC | BP PLC | Calumet, Inc. /DE | CONOCOPHILLIPS"
44,2300.0,APPAREL & OTHER FINISHD PRODS OF FABRICS & SIMILAR MATL,21,"AS, BIRD, BRIA, COLM, CRI, FIGS, GIII, GIL, GOOS, JRSH","Amer Sports, Inc. | Allbirds, Inc. | BrilliA Inc | COLUMBIA SPORTSWEAR CO | CARTERS INC"
353,7359.0,"SERVICES-EQUIPMENT RENTAL & LEASING, NEC",21,"AER, AL, AYR, CTOS, EHGO, EQPT, FPAY, KPLT, KPLTW, MGRC","AerCap Holdings N.V. | SUMISHO AIR LEASE CORP | Aircastle LTD | Custom Truck One Source, Inc. | EShallGo Inc."
385,8090.0,"SERVICES-MISC HEALTH & ALLIED SERVICES, NEC",21,"AGL, BRTX, CCEL, DVA, FMCQF, FMS, IMTH, MGRX, MRAI, NIVF","agilon health, inc. | BioRestorative Therapies, Inc. | CRYO CELL INTERNATIONAL INC | DAVITA INC. | Fresenius Medical..."
153,3577.0,"COMPUTER PERIPHERAL EQUIPMENT, NEC",20,"ALOT, CRSR, EVLV, EVLVW, FTNT, IMMR, INVE, LINK, LOGI, MITK","AstroNova, Inc. | Corsair Gaming, Inc. | Evolv Technologies Holdings, Inc. | Evolv Technologies Holdings, Inc. | For..."
158,3590.0,MISC INDUSTRIAL & COMMERCIAL MACHINERY & EQUIPMENT,20,"CLEV, CW, EPAC, ETN, HTOO, INQD, LIQT, MOG-A, MOG-B, NGTF",Concrete Leveling Systems Inc | CURTISS WRIGHT CORP | ENERPAC TOOL GROUP CORP | Eaton Corp plc | Fusion Fuel Green PLC
345,7200.0,SERVICES-PERSONAL SERVICES,20,"BGFR, CBCA, CSV, DLPN, DOGP, EM, EVI, EWCZ, HRB, MRM","BestGofer Inc. | Crown Baus Capital Corp. | CARRIAGE SERVICES INC | Dolphin Entertainment, Inc. | Dogecoin Cash, Inc."
75,2821.0,"PLASTIC MATERIALS, SYNTH RESINS & NONVULCAN ELASTOMERS",20,"ALB, ALB-PA, ASIX, AVNT, DD, DOW, EMN, HGYN, HXL, PCT","ALBEMARLE CORP | ALBEMARLE CORP | AdvanSix Inc. | AVIENT CORP | DuPont de Nemours, Inc."
347,7311.0,SERVICES-ADVERTISING AGENCIES,20,"CRTO, GRPN, HAO, INND, IPG, KDOZF, MCTR, OMC, QMMM, SPTY","Criteo S.A. | Groupon, Inc. | Haoxi Health Technology Ltd | INNERSCOPE HEARING TECHNOLOGIES, INC. | INTERPUBLIC GROU..."
339,6794.0,PATENT OWNERS & LESSORS,19,"ACTG, AERA, AMOD, AMODW, APPS, BKUH, DLB, FIGI, IDCC, ILST","ACACIA RESEARCH CORP | AI Era Corp. | ALPHA MODUS HOLDINGS, INC. | ALPHA MODUS HOLDINGS, INC. | Digital Turbine, Inc."
136,3533.0,OIL & GAS FIELD MACHINERY & EQUIPMENT,19,"BKR, DNOW, DTI, FET, FLOC, FTI, GPUS, GPUS-PD, INVX, KLNG","Baker Hughes Co | DNOW Inc. | Drilling Tools International Corp | FORUM ENERGY TECHNOLOGIES, INC. | Flowco Holdings ..."

In [41]:
fundamental_df[fundamental_df['ticker'] == 'ADP']

,Unnamed: 0,ticker,cik,name,sic,total_assets,total_liabilities,revenue,net_income,Office,Industry Title
149,149,ADP,8670,AUTOMATIC DATA PROCESSING INC,7374.0,5.336930e+10,4.718130e+10,2.056090e+10,4.079700e+09,Office of Technology,SERVICES-COMPUTER PROCESSING & DATA PREPARATION

In [42]:
sic_major_division_map = {
    range(100, 1000): "Agriculture",
    range(1000, 1500): "Mining / Energy",
    range(1500, 1800): "Construction",
    range(2000, 4000): "Manufacturing / Industrials",
    range(4000, 5000): "Transportation / Utilities",
    range(5000, 6000): "Wholesale / Retail",
    range(6000, 6800): "Finance / Insurance / Real Estate",
    range(7000, 9000): "Services",
    range(9100, 9730): "Public Administration",
}

In [43]:
# fundamental_df = fundamental_df[
#     fundamental_df["sic"] != 6770
# ]

# print(f"Remaining rows: {len(fundamental_df)}")

Remaining rows: 8219

In [44]:
# def map_sic_major_division(sic):
#     if pd.isna(sic):
#         return "Unknown"

#     sic = int(sic)

#     for sic_range, industry in sic_major_division_map.items():
#         if sic in sic_range:
#             return industry

#     return "Other"

In [46]:
# fundamental_df = fundamental_df.copy()
# fundamental_df["industry"] = (
#     fundamental_df["sic"]
#     .apply(map_sic_major_division)
# )

# fundamental_df["industry"].value_counts()

industry
Manufacturing / Industrials          2879
Finance / Insurance / Real Estate    1979
Services                             1560
Transportation / Utilities            704
Wholesale / Retail                    484
Mining / Energy                       463
Construction                           98
Agriculture                            52
Name: count, dtype: int64

In [48]:
# fundamental_df.to_csv("03_fundamental_universe_ticker_sic_industry.csv")

In [49]:
fundamental_df = pd.read_csv("03_fundamental_universe_ticker_sic_industry.csv")

In [50]:
# use_local_storage(True)

# output_file = "raw_financial_facts.csv"

# # Use your cleaned universe
# tickers = fundamental_df["ticker"].dropna().unique().tolist()

# # Resume logic
# if os.path.exists(output_file):
#     existing = pd.read_csv(output_file)
#     completed = set(existing["ticker"].unique())
#     print(f"Resuming. Completed tickers: {len(completed)}")
# else:
#     existing = pd.DataFrame()
#     completed = set()

# rows = []

# for ticker in tqdm(tickers):
#     if ticker in completed:
#         continue

#     try:
#         c = Company(ticker)
#         facts = c.get_facts()
#         df = facts.to_dataframe()

#         df["ticker"] = ticker
#         df["cik"] = c.cik
#         df["company_name"] = c.name
#         df["sic"] = c.sic

#         # Keep only accounting facts with numeric values
#         df = df[df["numeric_value"].notna()].copy()

#         # Optional: keep only annual + quarterly periods
#         df = df[df["fiscal_period"].isin(["FY", "Q1", "Q2", "Q3", "Q4"])]

#         rows.append(df)

#         # checkpoint every 25 companies
#         if len(rows) >= 25:
#             batch = pd.concat(rows, ignore_index=True)

#             if os.path.exists(output_file):
#                 batch.to_csv(output_file, mode="a", header=False, index=False)
#             else:
#                 batch.to_csv(output_file, index=False)

#             rows = []

#     except Exception as e:
#         print(f"Error for {ticker}: {e}")
#         continue

# # final save
# if rows:
#     batch = pd.concat(rows, ignore_index=True)

#     if os.path.exists(output_file):
#         batch.to_csv(output_file, mode="a", header=False, index=False)
#     else:
#         batch.to_csv(output_file, index=False)

# print("Done.")

100%|████████████████████████████████████████████████████████████████████████████| 8215/8215 [3:41:16<00:00,  1.62s/it]

Done.

In [3]:
# csv_file = "raw_financial_facts.csv"
# output_folder = "raw_financial_facts_parquet"

# os.makedirs(output_folder, exist_ok=True)

# chunksize = 250_000

# print("Starting CSV → Parquet chunk conversion...")

# for i, chunk in enumerate(
#     pd.read_csv(csv_file, chunksize=chunksize)
# ):
#     output_path = os.path.join(
#         output_folder,
#         f"part_{i:05d}.parquet"
#     )

#     # Save chunk as parquet
#     chunk.to_parquet(
#         output_path,
#         index=False
#     )

#     print(
#         f"Saved chunk {i} → {output_path} "
#         f"({len(chunk):,} rows)"
#     )

# print("Done. All chunks converted.")

Starting CSV → Parquet chunk conversion...
Saved chunk 0 → raw_financial_facts_parquet\part_00000.parquet (250,000 rows)
Saved chunk 1 → raw_financial_facts_parquet\part_00001.parquet (250,000 rows)
Saved chunk 2 → raw_financial_facts_parquet\part_00002.parquet (250,000 rows)
Saved chunk 3 → raw_financial_facts_parquet\part_00003.parquet (250,000 rows)
Saved chunk 4 → raw_financial_facts_parquet\part_00004.parquet (250,000 rows)
Saved chunk 5 → raw_financial_facts_parquet\part_00005.parquet (250,000 rows)
Saved chunk 6 → raw_financial_facts_parquet\part_00006.parquet (250,000 rows)
Saved chunk 7 → raw_financial_facts_parquet\part_00007.parquet (250,000 rows)
Saved chunk 8 → raw_financial_facts_parquet\part_00008.parquet (250,000 rows)
Saved chunk 9 → raw_financial_facts_parquet\part_00009.parquet (250,000 rows)
Saved chunk 10 → raw_financial_facts_parquet\part_00010.parquet (250,000 rows)
Saved chunk 11 → raw_financial_facts_parquet\part_00011.parquet (250,000 rows)
Saved chunk 12 → raw_financial_facts_parquet\part_00012.parquet (250,000 rows)
Saved chunk 13 → raw_financial_facts_parquet\part_00013.parquet (250,000 rows)
Saved chunk 14 → raw_financial_facts_parquet\part_00014.parquet (250,000 rows)
Saved chunk 15 → raw_financial_facts_parquet\part_00015.parquet (250,000 rows)
Saved chunk 16 → raw_financial_facts_parquet\part_00016.parquet (250,000 rows)
Saved chunk 17 → raw_financial_facts_parquet\part_00017.parquet (250,000 rows)
Saved chunk 18 → raw_financial_facts_parquet\part_00018.parquet (250,000 rows)
Saved chunk 19 → raw_financial_facts_parquet\part_00019.parquet (250,000 rows)
Saved chunk 20 → raw_financial_facts_parquet\part_00020.parquet (250,000 rows)
Saved chunk 21 → raw_financial_facts_parquet\part_00021.parquet (250,000 rows)
Saved chunk 22 → raw_financial_facts_parquet\part_00022.parquet (250,000 rows)
Saved chunk 23 → raw_financial_facts_parquet\part_00023.parquet (250,000 rows)
Saved chunk 24 → raw_financial_facts_parquet\part_00024.parquet (250,000 rows)
Saved chunk 25 → raw_financial_facts_parquet\part_00025.parquet (250,000 rows)
Saved chunk 26 → raw_financial_facts_parquet\part_00026.parquet (250,000 rows)
Saved chunk 27 → raw_financial_facts_parquet\part_00027.parquet (250,000 rows)
Saved chunk 28 → raw_financial_facts_parquet\part_00028.parquet (250,000 rows)
Saved chunk 29 → raw_financial_facts_parquet\part_00029.parquet (250,000 rows)
Saved chunk 30 → raw_financial_facts_parquet\part_00030.parquet (250,000 rows)
Saved chunk 31 → raw_financial_facts_parquet\part_00031.parquet (250,000 rows)
Saved chunk 32 → raw_financial_facts_parquet\part_00032.parquet (250,000 rows)
Saved chunk 33 → raw_financial_facts_parquet\part_00033.parquet (250,000 rows)
Saved chunk 34 → raw_financial_facts_parquet\part_00034.parquet (250,000 rows)
Saved chunk 35 → raw_financial_facts_parquet\part_00035.parquet (250,000 rows)
Saved chunk 36 → raw_financial_facts_parquet\part_00036.parquet (250,000 rows)
Saved chunk 37 → raw_financial_facts_parquet\part_00037.parquet (250,000 rows)
Saved chunk 38 → raw_financial_facts_parquet\part_00038.parquet (250,000 rows)
Saved chunk 39 → raw_financial_facts_parquet\part_00039.parquet (250,000 rows)
Saved chunk 40 → raw_financial_facts_parquet\part_00040.parquet (250,000 rows)
Saved chunk 41 → raw_financial_facts_parquet\part_00041.parquet (250,000 rows)
Saved chunk 42 → raw_financial_facts_parquet\part_00042.parquet (250,000 rows)
Saved chunk 43 → raw_financial_facts_parquet\part_00043.parquet (250,000 rows)
Saved chunk 44 → raw_financial_facts_parquet\part_00044.parquet (250,000 rows)
Saved chunk 45 → raw_financial_facts_parquet\part_00045.parquet (250,000 rows)
Saved chunk 46 → raw_financial_facts_parquet\part_00046.parquet (250,000 rows)
Saved chunk 47 → raw_financial_facts_parquet\part_00047.parquet (250,000 rows)
Saved chunk 48 → raw_financial_facts_parquet\part_00048.parquet (250,000 rows)
Saved chunk 49 → raw_financial_facts_parquet\part_00049.parquet (250,000 rows)
Saved chunk 50 → raw_financial_facts_parquet\part_00050.parquet (250,000 rows)
Saved chunk 51 → raw_financial_facts_parquet\part_00051.parquet (250,000 rows)
Saved chunk 52 → raw_financial_facts_parquet\part_00052.parquet (250,000 rows)
Saved chunk 53 → raw_financial_facts_parquet\part_00053.parquet (250,000 rows)
Saved chunk 54 → raw_financial_facts_parquet\part_00054.parquet (250,000 rows)
Saved chunk 55 → raw_financial_facts_parquet\part_00055.parquet (250,000 rows)
Saved chunk 56 → raw_financial_facts_parquet\part_00056.parquet (250,000 rows)
Saved chunk 57 → raw_financial_facts_parquet\part_00057.parquet (250,000 rows)
Saved chunk 58 → raw_financial_facts_parquet\part_00058.parquet (250,000 rows)
Saved chunk 59 → raw_financial_facts_parquet\part_00059.parquet (250,000 rows)
Saved chunk 60 → raw_financial_facts_parquet\part_00060.parquet (250,000 rows)
Saved chunk 61 → raw_financial_facts_parquet\part_00061.parquet (250,000 rows)
Saved chunk 62 → raw_financial_facts_parquet\part_00062.parquet (250,000 rows)
Saved chunk 63 → raw_financial_facts_parquet\part_00063.parquet (250,000 rows)
Saved chunk 64 → raw_financial_facts_parquet\part_00064.parquet (250,000 rows)
Saved chunk 65 → raw_financial_facts_parquet\part_00065.parquet (250,000 rows)
Saved chunk 66 → raw_financial_facts_parquet\part_00066.parquet (250,000 rows)
Saved chunk 67 → raw_financial_facts_parquet\part_00067.parquet (250,000 rows)
Saved chunk 68 → raw_financial_facts_parquet\part_00068.parquet (250,000 rows)
Saved chunk 69 → raw_financial_facts_parquet\part_00069.parquet (250,000 rows)
Saved chunk 70 → raw_financial_facts_parquet\part_00070.parquet (250,000 rows)
Saved chunk 71 → raw_financial_facts_parquet\part_00071.parquet (250,000 rows)
Saved chunk 72 → raw_financial_facts_parquet\part_00072.parquet (250,000 rows)
Saved chunk 73 → raw_financial_facts_parquet\part_00073.parquet (250,000 rows)
Saved chunk 74 → raw_financial_facts_parquet\part_00074.parquet (250,000 rows)
Saved chunk 75 → raw_financial_facts_parquet\part_00075.parquet (250,000 rows)
Saved chunk 76 → raw_financial_facts_parquet\part_00076.parquet (250,000 rows)
Saved chunk 77 → raw_financial_facts_parquet\part_00077.parquet (250,000 rows)
Saved chunk 78 → raw_financial_facts_parquet\part_00078.parquet (250,000 rows)
Saved chunk 79 → raw_financial_facts_parquet\part_00079.parquet (250,000 rows)
Saved chunk 80 → raw_financial_facts_parquet\part_00080.parquet (250,000 rows)
Saved chunk 81 → raw_financial_facts_parquet\part_00081.parquet (250,000 rows)
Saved chunk 82 → raw_financial_facts_parquet\part_00082.parquet (250,000 rows)
Saved chunk 83 → raw_financial_facts_parquet\part_00083.parquet (250,000 rows)
Saved chunk 84 → raw_financial_facts_parquet\part_00084.parquet (250,000 rows)
Saved chunk 85 → raw_financial_facts_parquet\part_00085.parquet (250,000 rows)
Saved chunk 86 → raw_financial_facts_parquet\part_00086.parquet (250,000 rows)
Saved chunk 87 → raw_financial_facts_parquet\part_00087.parquet (250,000 rows)
Saved chunk 88 → raw_financial_facts_parquet\part_00088.parquet (250,000 rows)
Saved chunk 89 → raw_financial_facts_parquet\part_00089.parquet (250,000 rows)
Saved chunk 90 → raw_financial_facts_parquet\part_00090.parquet (250,000 rows)
Saved chunk 91 → raw_financial_facts_parquet\part_00091.parquet (250,000 rows)
Saved chunk 92 → raw_financial_facts_parquet\part_00092.parquet (250,000 rows)
Saved chunk 93 → raw_financial_facts_parquet\part_00093.parquet (250,000 rows)
Saved chunk 94 → raw_financial_facts_parquet\part_00094.parquet (250,000 rows)
Saved chunk 95 → raw_financial_facts_parquet\part_00095.parquet (250,000 rows)
Saved chunk 96 → raw_financial_facts_parquet\part_00096.parquet (250,000 rows)
Saved chunk 97 → raw_financial_facts_parquet\part_00097.parquet (250,000 rows)
Saved chunk 98 → raw_financial_facts_parquet\part_00098.parquet (250,000 rows)
Saved chunk 99 → raw_financial_facts_parquet\part_00099.parquet (250,000 rows)
Saved chunk 100 → raw_financial_facts_parquet\part_00100.parquet (250,000 rows)
Saved chunk 101 → raw_financial_facts_parquet\part_00101.parquet (250,000 rows)
Saved chunk 102 → raw_financial_facts_parquet\part_00102.parquet (250,000 rows)
Saved chunk 103 → raw_financial_facts_parquet\part_00103.parquet (250,000 rows)
Saved chunk 104 → raw_financial_facts_parquet\part_00104.parquet (250,000 rows)
Saved chunk 105 → raw_financial_facts_parquet\part_00105.parquet (250,000 rows)
Saved chunk 106 → raw_financial_facts_parquet\part_00106.parquet (250,000 rows)
Saved chunk 107 → raw_financial_facts_parquet\part_00107.parquet (250,000 rows)
Saved chunk 108 → raw_financial_facts_parquet\part_00108.parquet (250,000 rows)
Saved chunk 109 → raw_financial_facts_parquet\part_00109.parquet (250,000 rows)
Saved chunk 110 → raw_financial_facts_parquet\part_00110.parquet (250,000 rows)
Saved chunk 111 → raw_financial_facts_parquet\part_00111.parquet (250,000 rows)
Saved chunk 112 → raw_financial_facts_parquet\part_00112.parquet (250,000 rows)
Saved chunk 113 → raw_financial_facts_parquet\part_00113.parquet (250,000 rows)
Saved chunk 114 → raw_financial_facts_parquet\part_00114.parquet (250,000 rows)
Saved chunk 115 → raw_financial_facts_parquet\part_00115.parquet (250,000 rows)
Saved chunk 116 → raw_financial_facts_parquet\part_00116.parquet (250,000 rows)
Saved chunk 117 → raw_financial_facts_parquet\part_00117.parquet (250,000 rows)
Saved chunk 118 → raw_financial_facts_parquet\part_00118.parquet (250,000 rows)
Saved chunk 119 → raw_financial_facts_parquet\part_00119.parquet (250,000 rows)
Saved chunk 120 → raw_financial_facts_parquet\part_00120.parquet (250,000 rows)
Saved chunk 121 → raw_financial_facts_parquet\part_00121.parquet (250,000 rows)
Saved chunk 122 → raw_financial_facts_parquet\part_00122.parquet (250,000 rows)
Saved chunk 123 → raw_financial_facts_parquet\part_00123.parquet (250,000 rows)
Saved chunk 124 → raw_financial_facts_parquet\part_00124.parquet (250,000 rows)
Saved chunk 125 → raw_financial_facts_parquet\part_00125.parquet (250,000 rows)
Saved chunk 126 → raw_financial_facts_parquet\part_00126.parquet (250,000 rows)
Saved chunk 127 → raw_financial_facts_parquet\part_00127.parquet (250,000 rows)
Saved chunk 128 → raw_financial_facts_parquet\part_00128.parquet (250,000 rows)
Saved chunk 129 → raw_financial_facts_parquet\part_00129.parquet (250,000 rows)
Saved chunk 130 → raw_financial_facts_parquet\part_00130.parquet (250,000 rows)
Saved chunk 131 → raw_financial_facts_parquet\part_00131.parquet (250,000 rows)
Saved chunk 132 → raw_financial_facts_parquet\part_00132.parquet (250,000 rows)
Saved chunk 133 → raw_financial_facts_parquet\part_00133.parquet (250,000 rows)
Saved chunk 134 → raw_financial_facts_parquet\part_00134.parquet (250,000 rows)
Saved chunk 135 → raw_financial_facts_parquet\part_00135.parquet (250,000 rows)
Saved chunk 136 → raw_financial_facts_parquet\part_00136.parquet (250,000 rows)
Saved chunk 137 → raw_financial_facts_parquet\part_00137.parquet (250,000 rows)
Saved chunk 138 → raw_financial_facts_parquet\part_00138.parquet (250,000 rows)
Saved chunk 139 → raw_financial_facts_parquet\part_00139.parquet (250,000 rows)
Saved chunk 140 → raw_financial_facts_parquet\part_00140.parquet (250,000 rows)
Saved chunk 141 → raw_financial_facts_parquet\part_00141.parquet (250,000 rows)
Saved chunk 142 → raw_financial_facts_parquet\part_00142.parquet (250,000 rows)
Saved chunk 143 → raw_financial_facts_parquet\part_00143.parquet (250,000 rows)
Saved chunk 144 → raw_financial_facts_parquet\part_00144.parquet (250,000 rows)
Saved chunk 145 → raw_financial_facts_parquet\part_00145.parquet (250,000 rows)
Saved chunk 146 → raw_financial_facts_parquet\part_00146.parquet (250,000 rows)
Saved chunk 147 → raw_financial_facts_parquet\part_00147.parquet (250,000 rows)
Saved chunk 148 → raw_financial_facts_parquet\part_00148.parquet (250,000 rows)
Saved chunk 149 → raw_financial_facts_parquet\part_00149.parquet (250,000 rows)
Saved chunk 150 → raw_financial_facts_parquet\part_00150.parquet (250,000 rows)
Saved chunk 151 → raw_financial_facts_parquet\part_00151.parquet (250,000 rows)
Saved chunk 152 → raw_financial_facts_parquet\part_00152.parquet (250,000 rows)
Saved chunk 153 → raw_financial_facts_parquet\part_00153.parquet (250,000 rows)
Saved chunk 154 → raw_financial_facts_parquet\part_00154.parquet (250,000 rows)
Saved chunk 155 → raw_financial_facts_parquet\part_00155.parquet (250,000 rows)
Saved chunk 156 → raw_financial_facts_parquet\part_00156.parquet (250,000 rows)
Saved chunk 157 → raw_financial_facts_parquet\part_00157.parquet (250,000 rows)
Saved chunk 158 → raw_financial_facts_parquet\part_00158.parquet (250,000 rows)
Saved chunk 159 → raw_financial_facts_parquet\part_00159.parquet (250,000 rows)
Saved chunk 160 → raw_financial_facts_parquet\part_00160.parquet (250,000 rows)
Saved chunk 161 → raw_financial_facts_parquet\part_00161.parquet (250,000 rows)
Saved chunk 162 → raw_financial_facts_parquet\part_00162.parquet (250,000 rows)
Saved chunk 163 → raw_financial_facts_parquet\part_00163.parquet (250,000 rows)
Saved chunk 164 → raw_financial_facts_parquet\part_00164.parquet (250,000 rows)
Saved chunk 165 → raw_financial_facts_parquet\part_00165.parquet (250,000 rows)
Saved chunk 166 → raw_financial_facts_parquet\part_00166.parquet (250,000 rows)
Saved chunk 167 → raw_financial_facts_parquet\part_00167.parquet (250,000 rows)
Saved chunk 168 → raw_financial_facts_parquet\part_00168.parquet (250,000 rows)
Saved chunk 169 → raw_financial_facts_parquet\part_00169.parquet (250,000 rows)
Saved chunk 170 → raw_financial_facts_parquet\part_00170.parquet (250,000 rows)
Saved chunk 171 → raw_financial_facts_parquet\part_00171.parquet (250,000 rows)
Saved chunk 172 → raw_financial_facts_parquet\part_00172.parquet (250,000 rows)
Saved chunk 173 → raw_financial_facts_parquet\part_00173.parquet (250,000 rows)
Saved chunk 174 → raw_financial_facts_parquet\part_00174.parquet (250,000 rows)
Saved chunk 175 → raw_financial_facts_parquet\part_00175.parquet (250,000 rows)
Saved chunk 176 → raw_financial_facts_parquet\part_00176.parquet (250,000 rows)
Saved chunk 177 → raw_financial_facts_parquet\part_00177.parquet (250,000 rows)
Saved chunk 178 → raw_financial_facts_parquet\part_00178.parquet (250,000 rows)
Saved chunk 179 → raw_financial_facts_parquet\part_00179.parquet (250,000 rows)
Saved chunk 180 → raw_financial_facts_parquet\part_00180.parquet (250,000 rows)
Saved chunk 181 → raw_financial_facts_parquet\part_00181.parquet (250,000 rows)
Saved chunk 182 → raw_financial_facts_parquet\part_00182.parquet (250,000 rows)
Saved chunk 183 → raw_financial_facts_parquet\part_00183.parquet (250,000 rows)
Saved chunk 184 → raw_financial_facts_parquet\part_00184.parquet (250,000 rows)
Saved chunk 185 → raw_financial_facts_parquet\part_00185.parquet (250,000 rows)
Saved chunk 186 → raw_financial_facts_parquet\part_00186.parquet (250,000 rows)
Saved chunk 187 → raw_financial_facts_parquet\part_00187.parquet (250,000 rows)
Saved chunk 188 → raw_financial_facts_parquet\part_00188.parquet (250,000 rows)
Saved chunk 189 → raw_financial_facts_parquet\part_00189.parquet (250,000 rows)
Saved chunk 190 → raw_financial_facts_parquet\part_00190.parquet (250,000 rows)
Saved chunk 191 → raw_financial_facts_parquet\part_00191.parquet (250,000 rows)
Saved chunk 192 → raw_financial_facts_parquet\part_00192.parquet (250,000 rows)
Saved chunk 193 → raw_financial_facts_parquet\part_00193.parquet (250,000 rows)
Saved chunk 194 → raw_financial_facts_parquet\part_00194.parquet (250,000 rows)
Saved chunk 195 → raw_financial_facts_parquet\part_00195.parquet (250,000 rows)
Saved chunk 196 → raw_financial_facts_parquet\part_00196.parquet (250,000 rows)
Saved chunk 197 → raw_financial_facts_parquet\part_00197.parquet (250,000 rows)
Saved chunk 198 → raw_financial_facts_parquet\part_00198.parquet (250,000 rows)
Saved chunk 199 → raw_financial_facts_parquet\part_00199.parquet (250,000 rows)
Saved chunk 200 → raw_financial_facts_parquet\part_00200.parquet (250,000 rows)
Saved chunk 201 → raw_financial_facts_parquet\part_00201.parquet (250,000 rows)
Saved chunk 202 → raw_financial_facts_parquet\part_00202.parquet (250,000 rows)
Saved chunk 203 → raw_financial_facts_parquet\part_00203.parquet (250,000 rows)
Saved chunk 204 → raw_financial_facts_parquet\part_00204.parquet (250,000 rows)
Saved chunk 205 → raw_financial_facts_parquet\part_00205.parquet (250,000 rows)
Saved chunk 206 → raw_financial_facts_parquet\part_00206.parquet (250,000 rows)
Saved chunk 207 → raw_financial_facts_parquet\part_00207.parquet (250,000 rows)
Saved chunk 208 → raw_financial_facts_parquet\part_00208.parquet (250,000 rows)
Saved chunk 209 → raw_financial_facts_parquet\part_00209.parquet (250,000 rows)
Saved chunk 210 → raw_financial_facts_parquet\part_00210.parquet (250,000 rows)
Saved chunk 211 → raw_financial_facts_parquet\part_00211.parquet (250,000 rows)
Saved chunk 212 → raw_financial_facts_parquet\part_00212.parquet (250,000 rows)
Saved chunk 213 → raw_financial_facts_parquet\part_00213.parquet (250,000 rows)
Saved chunk 214 → raw_financial_facts_parquet\part_00214.parquet (250,000 rows)
Saved chunk 215 → raw_financial_facts_parquet\part_00215.parquet (250,000 rows)
Saved chunk 216 → raw_financial_facts_parquet\part_00216.parquet (250,000 rows)
Saved chunk 217 → raw_financial_facts_parquet\part_00217.parquet (250,000 rows)
Saved chunk 218 → raw_financial_facts_parquet\part_00218.parquet (250,000 rows)
Saved chunk 219 → raw_financial_facts_parquet\part_00219.parquet (250,000 rows)
Saved chunk 220 → raw_financial_facts_parquet\part_00220.parquet (250,000 rows)
Saved chunk 221 → raw_financial_facts_parquet\part_00221.parquet (250,000 rows)
Saved chunk 222 → raw_financial_facts_parquet\part_00222.parquet (250,000 rows)
Saved chunk 223 → raw_financial_facts_parquet\part_00223.parquet (250,000 rows)
Saved chunk 224 → raw_financial_facts_parquet\part_00224.parquet (250,000 rows)
Saved chunk 225 → raw_financial_facts_parquet\part_00225.parquet (250,000 rows)
Saved chunk 226 → raw_financial_facts_parquet\part_00226.parquet (250,000 rows)
Saved chunk 227 → raw_financial_facts_parquet\part_00227.parquet (250,000 rows)
Saved chunk 228 → raw_financial_facts_parquet\part_00228.parquet (250,000 rows)
Saved chunk 229 → raw_financial_facts_parquet\part_00229.parquet (250,000 rows)
Saved chunk 230 → raw_financial_facts_parquet\part_00230.parquet (250,000 rows)
Saved chunk 231 → raw_financial_facts_parquet\part_00231.parquet (250,000 rows)
Saved chunk 232 → raw_financial_facts_parquet\part_00232.parquet (250,000 rows)
Saved chunk 233 → raw_financial_facts_parquet\part_00233.parquet (250,000 rows)
Saved chunk 234 → raw_financial_facts_parquet\part_00234.parquet (250,000 rows)
Saved chunk 235 → raw_financial_facts_parquet\part_00235.parquet (250,000 rows)
Saved chunk 236 → raw_financial_facts_parquet\part_00236.parquet (250,000 rows)
Saved chunk 237 → raw_financial_facts_parquet\part_00237.parquet (250,000 rows)
Saved chunk 238 → raw_financial_facts_parquet\part_00238.parquet (250,000 rows)
Saved chunk 239 → raw_financial_facts_parquet\part_00239.parquet (250,000 rows)
Saved chunk 240 → raw_financial_facts_parquet\part_00240.parquet (250,000 rows)
Saved chunk 241 → raw_financial_facts_parquet\part_00241.parquet (250,000 rows)
Saved chunk 242 → raw_financial_facts_parquet\part_00242.parquet (250,000 rows)
Saved chunk 243 → raw_financial_facts_parquet\part_00243.parquet (250,000 rows)
Saved chunk 244 → raw_financial_facts_parquet\part_00244.parquet (250,000 rows)
Saved chunk 245 → raw_financial_facts_parquet\part_00245.parquet (250,000 rows)
Saved chunk 246 → raw_financial_facts_parquet\part_00246.parquet (250,000 rows)
Saved chunk 247 → raw_financial_facts_parquet\part_00247.parquet (250,000 rows)
Saved chunk 248 → raw_financial_facts_parquet\part_00248.parquet (250,000 rows)
Saved chunk 249 → raw_financial_facts_parquet\part_00249.parquet (250,000 rows)

In [5]:
files = glob.glob("raw_financial_facts_parquet/*.parquet")

print("Parquet files:", len(files))

total_size_gb = sum(os.path.getsize(f) for f in files) / 1e9
print("Total parquet size:", round(total_size_gb, 2), "GB")

Parquet files: 401
Total parquet size: 0.79 GB

In [9]:
con = duckdb.connect("financials.duckdb")

con.execute("""
CREATE OR REPLACE VIEW raw_facts AS
SELECT *
FROM read_parquet('raw_financial_facts_parquet/*.parquet')
""")

summary = con.execute("""
SELECT
    COUNT(*) AS rows,
    COUNT(DISTINCT ticker) AS tickers,
    COUNT(DISTINCT concept) AS concepts,
    MIN(fiscal_year) AS min_year,
    MAX(fiscal_year) AS max_year
FROM raw_facts
""").df()

summary

        rows  tickers  concepts  min_year  max_year
0  100149899     8194     13256         0     44012

In [10]:
con.execute("""
SELECT fiscal_year, COUNT(*) AS n
FROM raw_facts
GROUP BY fiscal_year
ORDER BY fiscal_year
LIMIT 30
""").df()

    fiscal_year        n
0             0     1809
1          1215      768
2          1905     2531
3          2004       88
4          2005       85
5          2006       85
6          2007       88
7          2008      680
8          2009   415440
9          2010  1307570
10         2011  3200033
11         2012  4519617
12         2013  4875196
13         2014  5049737
14         2015  5424876
15         2016  5526879
16         2017  5938218
17         2018  6250707
18         2019  6973405
19         2020  7239798
20         2021  7831400
21         2022  8441749
22         2023  8715003
23         2024  8912908
24         2025  8852343
25         2026   662214
26         2027      542
27         2107      700
28        43101      711
29        43465     1522

In [11]:
con.execute("""
CREATE OR REPLACE TABLE credit_model_base AS
SELECT *
FROM raw_facts
WHERE fiscal_year BETWEEN 2020 AND 2025
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [12]:
con.execute("""
SELECT
    COUNT(*) AS rows,
    COUNT(DISTINCT ticker) AS tickers,
    COUNT(DISTINCT concept) AS concepts
FROM credit_model_base
""").df()

       rows  tickers  concepts
0  49993201     8119     10870

In [13]:
concept_counts = con.execute("""
SELECT
    concept,
    label,
    COUNT(*) AS row_count,
    COUNT(DISTINCT ticker) AS ticker_coverage
FROM credit_model_base
GROUP BY concept, label
ORDER BY ticker_coverage DESC
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [14]:
concept_counts

,concept,label,row_count,ticker_coverage
0,us-gaap:Assets,Assets,290880,7169
1,us-gaap:NetCashProvidedByUsedInOperatingActivities,Net Cash Provided by (Used in) Operating Activities,300018,7143
2,us-gaap:NetCashProvidedByUsedInFinancingActivities,Net Cash Provided by (Used in) Financing Activities,293416,7132
3,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,280544,7104
4,dei:EntityCommonStockSharesOutstanding,"Entity Common Stock, Shares Outstanding",126179,7102
...,...,...,...,...
10865,us-gaap:TheatricalFilmCostsPreproduction,"Theatrical Film Costs, Preproduction",2,1
10866,us-gaap:DiscontinuedOperationIncomeLossFromDiscontinuedOperationDuringPhaseOutPeriodBeforeIncomeTaxAttributableToNon...,"Discontinued Operation, Income (Loss) from Discontinued Operation During Phase-out Period, before Income Tax, Attrib...",42,1
10867,us-gaap:DebtorReorganizationItemsRetireeRelatedCharges,"Debtor Reorganization Items, Retiree Related Charges",1,1
10868,ifrs-full:ReclassificationAdjustmentsOnApplicationOfOverlayApproachBeforeTax,None,2,1
10869,us-gaap:CertainLoansAcquiredInTransferAccountedForAsDebtSecuritiesAcquiredDuringPeriodContractuallyRequiredPaymentsR...,"Certain Loans Acquired in Transfer Accounted for as Debt Securities, Acquired During Period, Contractually Required ...",6,1

In [15]:
top_concepts = con.execute("""
SELECT
    concept,
    label,
    COUNT(*) AS row_count,
    COUNT(DISTINCT ticker) AS ticker_coverage
FROM credit_model_base
GROUP BY concept, label
ORDER BY ticker_coverage DESC
LIMIT 200
""").df()

top_concepts

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,concept,label,row_count,ticker_coverage
0,us-gaap:Assets,Assets,290880,7169
1,us-gaap:NetCashProvidedByUsedInOperatingActivities,Net Cash Provided by (Used in) Operating Activities,300018,7143
2,us-gaap:NetCashProvidedByUsedInFinancingActivities,Net Cash Provided by (Used in) Financing Activities,293416,7132
3,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,280544,7104
4,dei:EntityCommonStockSharesOutstanding,"Entity Common Stock, Shares Outstanding",126179,7102
5,us-gaap:NetIncomeLoss,Net Income (Loss) Attributable to Parent,506668,7036
6,us-gaap:NetCashProvidedByUsedInInvestingActivities,Net Cash Provided by (Used in) Investing Activities,276836,6941
7,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,518366,6938
8,us-gaap:RetainedEarningsAccumulatedDeficit,Retained Earnings (Accumulated Deficit),271400,6897
9,us-gaap:WeightedAverageNumberOfSharesOutstandingBasic,"Weighted Average Number of Shares Outstanding, Basic",366649,6712
10,us-gaap:EarningsPerShareBasic,"Earnings Per Share, Basic",383666,6711
11,us-gaap:WeightedAverageNumberOfDilutedSharesOutstanding,"Weighted Average Number of Shares Outstanding, Diluted",354594,6671
12,us-gaap:EarningsPerShareDiluted,"Earnings Per Share, Diluted",370274,6656
13,us-gaap:Liabilities,Liabilities,246256,6510
14,us-gaap:CashAndCashEquivalentsAtCarryingValue,"Cash and Cash Equivalents, at Carrying Value",271807,6495
15,us-gaap:IncomeTaxExpenseBenefit,Income Tax Expense (Benefit),348843,6445
16,dei:EntityPublicFloat,Entity Public Float,36632,6391
17,us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents,"Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents",394319,6168
18,us-gaap:EffectiveIncomeTaxRateReconciliationAtFederalStatutoryIncomeTaxRate,"Effective Income Tax Rate Reconciliation, at Federal Statutory Income Tax Rate, Percent",90529,6148
19,us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect,"Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Excha...",239053,6131
20,us-gaap:CommonStockSharesIssued,"Common Stock, Shares, Issued",221974,6114
21,us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest,"Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest",307433,6093
22,us-gaap:CommonStockSharesAuthorized,"Common Stock, Shares Authorized",229442,6050
23,us-gaap:DeferredTaxAssetsValuationAllowance,"Deferred Tax Assets, Valuation Allowance",75536,6005
24,us-gaap:PropertyPlantAndEquipmentNet,"Property, Plant and Equipment, Net",204875,5984
25,us-gaap:CommonStockValue,"Common Stock, Value, Issued",224096,5976
26,us-gaap:OperatingLeaseRightOfUseAsset,"Operating Lease, Right-of-Use Asset",189019,5953
27,us-gaap:CommonStockSharesOutstanding,"Common Stock, Shares, Outstanding",213970,5877
28,us-gaap:OperatingLeaseLiability,"Operating Lease, Liability",109091,5871
29,us-gaap:CommonStockParOrStatedValuePerShare,"Common Stock, Par or Stated Value Per Share",219600,5849
30,us-gaap:OperatingIncomeLoss,Operating Income (Loss),344760,5829
31,us-gaap:InterestPaidNet,"Interest Paid, Excluding Capitalized Interest, Operating Activities",183248,5820
32,us-gaap:ShareBasedCompensation,"Share-based Payment Arrangement, Noncash Expense",233386,5792
33,us-gaap:EffectiveIncomeTaxRateContinuingOperations,"Effective Income Tax Rate Reconciliation, Percent",158459,5756
34,us-gaap:LesseeOperatingLeaseLiabilityPaymentsDue,"Lessee, Operating Lease, Liability, to be Paid",67435,5721
35,us-gaap:LiabilitiesCurrent,"Liabilities, Current",213941,5700
36,us-gaap:AssetsCurrent,"Assets, Current",214173,5697
37,us-gaap:LesseeOperatingLeaseLiabilityPaymentsDueNextTwelveMonths,"Lessee, Operating Lease, Liability, to be Paid, Year One",60770,5641
38,us-gaap:LesseeOperatingLeaseLiabilityPaymentsDueYearTwo,"Lessee, Operating Lease, Liability, to be Paid, Year Two",62946,5601
39,us-gaap:LesseeOperatingLeaseLiabilityUndiscountedExcessAmount,"Lessee, Operating Lease, Liability, Undiscounted Excess Amount",63469,5522
40,us-gaap:LesseeOperatingLeaseLiabilityPaymentsDueYearThree,"Lessee, Operating Lease, Liability, to be Paid, Year Three",59447,5435
41,us-gaap:AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment,"Accumulated Depreciation, Depletion and Amortization, Property, Plant, and Equipment",128360,5419
42,us-gaap:DeferredTaxAssetsGross,"Deferred Tax Assets, Gross",58058,5382
43,us-gaap:OperatingLeaseWeightedAverageDiscountRatePercent,"Operating Lease, Weighted Average Discount Rate, Percent",100244,5349
44,us-gaap:IncomeTaxReconciliationIncomeTaxExpenseBenefitAtFederalStatutoryIncomeTaxRate,"Effective Income Tax Rate Reconciliation at Federal Statutory Income Tax Rate, Amount",56855,5277
45,us-gaap:ComprehensiveIncomeNetOfTax,"Comprehensive Income (Loss), Net of Tax, Attributable to Parent",289373,5203
46,us-gaap:PaymentsToAcquirePropertyPlantAndEquipment,"Payments to Acquire Property, Plant, and Equipment",184501,5145
47,us-gaap:LesseeOperatingLeaseLiabilityPaymentsDueYearFour,"Lessee, Operating Lease, Liability, to be Paid, Year Four",54756,5124
48,us-gaap:AccumulatedOtherComprehensiveIncomeLossNetOfTax,"Accumulated Other Comprehensive Income (Loss), Net of Tax",195238,5110
49,us-gaap:IncomeTaxesPaidNet,"Income Taxes Paid, Net",116401,5108
50,us-gaap:NumberOfReportableSegments,Number of Reportable Segments,51855,5092
51,us-gaap:PropertyPlantAndEquipmentGross,"Property, Plant and Equipment, Gross",108077,5054
52,us-gaap:DeferredIncomeTaxExpenseBenefit,Deferred Income Tax Expense (Benefit),133332,5012
53,us-gaap:DeferredTaxAssetsOperatingLossCarryforwards,"Deferred Tax Assets, Operating Loss Carryforwards",49812,4904
54,us-gaap:ProfitLoss,"Net Income (Loss), Including Portion Attributable to Noncontrolling Interest",246205,4897
55,us-gaap:InterestExpense,Interest Expense,210513,4888
56,us-gaap:OperatingLeaseLiabilityCurrent,"Operating Lease, Liability, Current",142107,4856
57,us-gaap:StockIssuedDuringPeriodValueNewIssues,"Stock Issued During Period, Value, New Issues",87952,4848
58,us-gaap:Depreciation,Depreciation,149581,4831
59,us-gaap:OperatingLeaseLiabilityNoncurrent,"Operating Lease, Liability, Noncurrent",146150,4825
60,us-gaap:PreferredStockSharesAuthorized,"Preferred Stock, Shares Authorized",156524,4783
61,us-gaap:LesseeOperatingLeaseLiabilityPaymentsDueYearFive,"Lessee, Operating Lease, Liability, to be Paid, Year Five",32371,4764
62,us-gaap:DeferredTaxAssetsNet,"Deferred Tax Assets, Net of Valuation Allowance",47620,4742
63,us-gaap:AdditionalPaidInCapital,Additional Paid in Capital,158383,4680
64,us-gaap:OperatingLeasePayments,"Operating Lease, Payments",120087,4653
65,us-gaap:AccountsPayableCurrent,"Accounts Payable, Current",159827,4644
66,us-gaap:EffectiveIncomeTaxRateReconciliationStateAndLocalIncomeTaxes,"Effective Income Tax Rate Reconciliation, State and Local Income Taxes, Percent",47984,4638
67,us-gaap:CurrentIncomeTaxExpenseBenefit,Current Income Tax Expense (Benefit),70088,4537
68,us-gaap:AllocatedShareBasedCompensationExpense,"Share-based Payment Arrangement, Expense",165931,4522
69,us-gaap:DeferredIncomeTaxLiabilities,"Deferred Tax Liabilities, Gross",46622,4490
70,us-gaap:LesseeOperatingLeaseLiabilityPaymentsDueAfterYearFive,"Lessee, Operating Lease, Liability, to be Paid, after Year Five",31120,4486
71,us-gaap:RightOfUseAssetObtainedInExchangeForOperatingLeaseLiability,Right-of-Use Asset Obtained in Exchange for Operating Lease Liability,99507,4480
72,us-gaap:AntidilutiveSecuritiesExcludedFromComputationOfEarningsPerShareAmount,"Antidilutive Securities Excluded from Computation of Earnings Per Share, Amount",166145,4468
73,us-gaap:OperatingLeaseCost,"Operating Lease, Cost",131985,4453
74,us-gaap:UnrecognizedTaxBenefits,Unrecognized Tax Benefits,84716,4414
75,us-gaap:OtherNonoperatingIncomeExpense,Other Nonoperating Income (Expense),205529,4359
76,us-gaap:AccountsReceivableNetCurrent,"Accounts Receivable, after Allowance for Credit Loss, Current",140384,4336
77,us-gaap:IncomeTaxReconciliationChangeInDeferredTaxAssetsValuationAllowance,"Effective Income Tax Rate Reconciliation, Change in Deferred Tax Assets Valuation Allowance, Amount",40500,4321
78,us-gaap:CurrentFederalTaxExpenseBenefit,Current Federal Tax Expense (Benefit),60458,4300
79,us-gaap:PreferredStockParOrStatedValuePerShare,"Preferred Stock, Par or Stated Value Per Share",138286,4291
80,us-gaap:DeferredFederalIncomeTaxExpenseBenefit,Deferred Federal Income Tax Expense (Benefit),60990,4288
81,us-gaap:IncreaseDecreaseInAccountsReceivable,Increase (Decrease) in Accounts Receivable,146852,4286
82,us-gaap:AmortizationOfIntangibleAssets,Amortization of Intangible Assets,167879,4282
83,us-gaap:IncomeTaxReconciliationStateAndLocalIncomeTaxes,"Effective Income Tax Rate Reconciliation, State and Local Income Taxes, Amount",42664,4271
84,us-gaap:DeferredTaxAssetsOther,"Deferred Tax Assets, Other",42068,4269
85,us-gaap:ProceedsFromIssuanceOfCommonStock,Proceeds from Issuance of Common Stock,85863,4239
86,us-gaap:GeneralAndAdministrativeExpense,General and Administrative Expense,211686,4232
87,us-gaap:Goodwill,Goodwill,165023,4187
88,us-gaap:CurrentStateAndLocalTaxExpenseBenefit,Current State and Local Tax Expense (Benefit),58860,4148
89,us-gaap:OtherAssetsNoncurrent,"Other Assets, Noncurrent",142895,4104
90,us-gaap:OperatingExpenses,Operating Expenses,199873,4081
91,us-gaap:EffectiveIncomeTaxRateReconciliationChangeInDeferredTaxAssetsValuationAllowance,"Effective Income Tax Rate Reconciliation, Change in Deferred Tax Assets Valuation Allowance, Percent",37317,4075
92,us-gaap:DepreciationDepletionAndAmortization,"Depreciation, Depletion and Amortization",158385,4062
93,us-gaap:FiniteLivedIntangibleAssetsNet,"Finite-Lived Intangible Assets, Net",97688,4060
94,us-gaap:AdjustmentsToAdditionalPaidInCapitalSharebasedCompensationRequisiteServicePeriodRecognitionValue,"APIC, Share-based Payment Arrangement, Increase for Cost Recognition",218236,4055
95,us-gaap:NumberOfOperatingSegments,Number of Operating Segments,38968,4055
96,us-gaap:FiniteLivedIntangibleAssetsAccumulatedAmortization,"Finite-Lived Intangible Assets, Accumulated Amortization",101975,4024
97,us-gaap:PreferredStockSharesIssued,"Preferred Stock, Shares Issued",118597,4008
98,us-gaap:NetIncomeLossAvailableToCommonStockholdersBasic,"Net Income (Loss) Available to Common Stockholders, Basic",175804,3905
99,us-gaap:DeferredStateAndLocalIncomeTaxExpenseBenefit,Deferred State and Local Income Tax Expense (Benefit),53895,3840
100,us-gaap:Revenues,Revenues,175797,3838
101,us-gaap:EffectiveIncomeTaxRateReconciliationOtherAdjustments,"Effective Income Tax Rate Reconciliation, Other Adjustments, Percent",37618,3825
102,us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax,"Revenue from Contract with Customer, Excluding Assessed Tax",207541,3806
103,us-gaap:PreferredStockSharesOutstanding,"Preferred Stock, Shares Outstanding",107328,3806
104,us-gaap:FiniteLivedIntangibleAssetsAmortizationExpenseNextTwelveMonths,"Finite-Lived Intangible Asset, Expected Amortization, Year One",37234,3793
105,us-gaap:PaymentsForRepurchaseOfCommonStock,Payments for Repurchase of Common Stock,115056,3787
106,us-gaap:LongTermDebt,Long-term Debt,81867,3787
107,us-gaap:FiniteLivedIntangibleAssetsAmortizationExpenseYearTwo,"Finite-Lived Intangible Asset, Expected Amortization, Year Two",38233,3771
108,us-gaap:FiniteLivedIntangibleAssetsAmortizationExpenseYearThree,"Finite-Lived Intangible Asset, Expected Amortization, Year Three",37385,3734
109,us-gaap:DeferredTaxAssetsLiabilitiesNet,"Deferred Tax Assets, Net",32833,3728
110,us-gaap:IncomeTaxReconciliationOtherAdjustments,"Effective Income Tax Rate Reconciliation, Other Adjustments, Amount",37317,3716
111,us-gaap:FiniteLivedIntangibleAssetsAmortizationExpenseYearFour,"Finite-Lived Intangible Asset, Expected Amortization, Year Four",35818,3654
112,us-gaap:ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsOutstandingNumber,"Share-based Compensation Arrangement by Share-based Payment Award, Options, Outstanding, Number",85679,3622
113,us-gaap:NonoperatingIncomeExpense,Nonoperating Income (Expense),162624,3573
114,us-gaap:PrepaidExpenseAndOtherAssetsCurrent,"Prepaid Expense and Other Assets, Current",116180,3570
115,us-gaap:DeferredTaxLiabilities,"Deferred Tax Liabilities, Net",30250,3540
116,us-gaap:LeaseCost,"Lease, Cost",104216,3514
117,us-gaap:AccruedLiabilitiesCurrent,"Accrued Liabilities, Current",106407,3507
118,us-gaap:FiniteLivedIntangibleAssetsAmortizationExpenseYearFive,"Finite-Lived Intangible Asset, Expected Amortization, Year Five",22397,3478
119,us-gaap:IntangibleAssetsNetExcludingGoodwill,"Intangible Assets, Net (Excluding Goodwill)",106878,3471
120,us-gaap:IncreaseDecreaseInPrepaidDeferredExpenseAndOtherAssets,Increase (Decrease) in Prepaid Expense and Other Assets,119021,3458
121,us-gaap:OtherLiabilitiesNoncurrent,"Other Liabilities, Noncurrent",118293,3457
122,us-gaap:StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest,"Stockholders' Equity, Including Portion Attributable to Noncontrolling Interest",247823,3393
123,us-gaap:InventoryNet,"Inventory, Net",115405,3359
124,us-gaap:LesseeOperatingLeaseLiabilityPaymentsRemainderOfFiscalYear,"Lessee, Operating Lease, Liability, to be Paid, Remainder of Fiscal Year",31779,3358
125,us-gaap:ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsOutstandingWeightedAverageExercisePrice,"Share-based Compensation Arrangement by Share-based Payment Award, Options, Outstanding, Weighted Average Exercise P...",79226,3346
126,us-gaap:GrossProfit,Gross Profit,172268,3345
127,us-gaap:PreferredStockValue,"Preferred Stock, Value, Issued",94973,3305
128,us-gaap:GainsLossesOnExtinguishmentOfDebt,Gain (Loss) on Extinguishment of Debt,74345,3302
129,us-gaap:IncreaseDecreaseInAccountsPayable,Increase (Decrease) in Accounts Payable,111154,3294
130,us-gaap:FiniteLivedIntangibleAssetsGross,"Finite-Lived Intangible Assets, Gross",75228,3280
131,us-gaap:IncreaseDecreaseInInventories,Increase (Decrease) in Inventories,118145,3269
132,us-gaap:ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsGrantsInPeriodGross,"Share-based Compensation Arrangement by Share-based Payment Award, Options, Grants in Period, Gross",43643,3269
133,us-gaap:StockIssuedDuringPeriodSharesStockOptionsExercised,"Share-based Compensation Arrangement by Share-based Payment Award, Options, Exercises in Period",41173,3266
134,us-gaap:DeferredTaxLiabilitiesPropertyPlantAndEquipment,"Deferred Tax Liabilities, Property, Plant and Equipment",30773,3213
135,us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxesDomestic,"Income (Loss) from Continuing Operations before Income Taxes, Domestic",42549,3182
136,us-gaap:DeferredTaxLiabilitiesOther,"Deferred Tax Liabilities, Other",28474,3151
137,us-gaap:GoodwillImpairmentLoss,"Goodwill, Impairment Loss",48660,3106
138,us-gaap:ResearchAndDevelopmentExpense,Research and Development Expense,143525,3092
139,us-gaap:LongTermDebtMaturitiesRepaymentsOfPrincipalInYearTwo,"Long-Term Debt, Maturity, Year Two",25246,3052
140,us-gaap:LongTermDebtMaturitiesRepaymentsOfPrincipalInNextTwelveMonths,"Long-Term Debt, Maturity, Year One",24334,3038
141,us-gaap:ShareBasedCompensationArrangementsByShareBasedPaymentAwardOptionsGrantsInPeriodWeightedAverageExercisePrice,"Share-based Compensation Arrangements by Share-based Payment Award, Options, Grants in Period, Weighted Average Exer...",35136,3011
142,us-gaap:PaymentsToAcquireBusinessesNetOfCashAcquired,"Payments to Acquire Businesses, Net of Cash Acquired",62808,3005
143,us-gaap:ProvisionForDoubtfulAccounts,"Accounts Receivable, Credit Loss Expense (Reversal)",77090,2964
144,us-gaap:LongTermDebtMaturitiesRepaymentsOfPrincipalInYearThree,"Long-Term Debt, Maturity, Year Three",24188,2955
145,us-gaap:ProceedsFromStockOptionsExercised,Proceeds from Stock Options Exercised,72998,2946
146,us-gaap:ValuationAllowanceDeferredTaxAssetChangeInAmount,"Valuation Allowance, Deferred Tax Asset, Increase (Decrease), Amount",22581,2943
147,us-gaap:OtherAccruedLiabilitiesCurrent,"Other Accrued Liabilities, Current",73797,2936
148,us-gaap:OtherComprehensiveIncomeLossNetOfTax,"Other Comprehensive Income (Loss), Net of Tax",158660,2898
149,us-gaap:DeferredIncomeTaxLiabilitiesNet,"Deferred Income Tax Liabilities, Net",85935,2889
150,us-gaap:CurrentForeignTaxExpenseBenefit,Current Foreign Tax Expense (Benefit),39373,2880
151,us-gaap:ShareBasedCompensationArrangementsByShareBasedPaymentAwardOptionsExercisesInPeriodWeightedAverageExercisePrice,"Share-based Compensation Arrangements by Share-based Payment Award, Options, Exercises in Period, Weighted Average E...",33021,2879
152,us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxesForeign,"Income (Loss) from Continuing Operations before Income Taxes, Foreign",35948,2872
153,us-gaap:StockIssuedDuringPeriodValueStockOptionsExercised,"Stock Issued During Period, Value, Stock Options Exercised",87160,2863
154,us-gaap:EmployeeRelatedLiabilitiesCurrent,"Employee-related Liabilities, Current",85693,2837
155,us-gaap:LongTermDebtMaturitiesRepaymentsOfPrincipalInYearFour,"Long-Term Debt, Maturity, Year Four",22264,2830
156,us-gaap:AllowanceForDoubtfulAccountsReceivableCurrent,"Accounts Receivable, Allowance for Credit Loss, Current",84148,2825
157,us-gaap:ContractWithCustomerLiabilityCurrent,"Contract with Customer, Liability, Current",80186,2807
158,us-gaap:DepreciationAndAmortization,"Depreciation, Depletion and Amortization, Nonproduction",110202,2801
159,us-gaap:ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsExercisableNumber,"Share-based Compensation Arrangement by Share-based Payment Award, Options, Exercisable, Number",31863,2783
160,us-gaap:DeferredTaxAssetsTaxDeferredExpenseCompensationAndBenefitsShareBasedCompensationCost,"Deferred Tax Assets, Tax Deferred Expense, Compensation and Benefits, Share-based Compensation Cost",27088,2747
161,us-gaap:AssetImpairmentCharges,Asset Impairment Charges,47672,2737
162,us-gaap:ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsOutstandingIntrinsicValue,"Share-based Compensation Arrangement by Share-based Payment Award, Options, Outstanding, Intrinsic Value",40682,2728
163,us-gaap:AdditionalPaidInCapitalCommonStock,"Additional Paid in Capital, Common Stock",93697,2718
164,us-gaap:LongTermDebtNoncurrent,"Long-term Debt, Excluding Current Maturities",78415,2716
165,us-gaap:DeferredIncomeTaxAssetsNet,"Deferred Income Tax Assets, Net",72946,2704
166,us-gaap:UnrecognizedTaxBenefitsIncreasesResultingFromCurrentPeriodTaxPositions,"Unrecognized Tax Benefits, Increase Resulting from Current Period Tax Positions",33674,2702
167,us-gaap:PrepaidExpenseCurrent,"Prepaid Expense, Current",59039,2664
168,us-gaap:InterestExpenseNonoperating,None,41657,2645
169,us-gaap:NetIncomeLossAttributableToNoncontrollingInterest,Net Income (Loss) Attributable to Noncontrolling Interest,119216,2643
170,us-gaap:DeferredForeignIncomeTaxExpenseBenefit,Deferred Foreign Income Tax Expense (Benefit),35556,2642
171,us-gaap:ProceedsFromSaleOfPropertyPlantAndEquipment,"Proceeds from Sale of Property, Plant, and Equipment",53052,2626
172,us-gaap:OtherAssetsCurrent,"Other Assets, Current",72120,2614
173,us-gaap:OtherLiabilitiesCurrent,"Other Liabilities, Current",64350,2611
174,us-gaap:IncreaseDecreaseInAccountsPayableAndAccruedLiabilities,Increase (Decrease) in Accounts Payable and Accrued Liabilities,90123,2600
175,us-gaap:IncomeTaxesPaid,Income Taxes Paid,55551,2593
176,us-gaap:LongTermDebtMaturitiesRepaymentsOfPrincipalInYearFive,"Long-Term Debt, Maturity, Year Five",14761,2592

In [ ]:
target_concepts = [
    "us-gaap:Assets",
    "us-gaap:AssetsCurrent",
    "us-gaap:Liabilities",
    "us-gaap:LiabilitiesCurrent",
    "us-gaap:CashAndCashEquivalentsAtCarryingValue",
    "us-gaap:AccountsReceivableNetCurrent",
    "us-gaap:InventoryNet",
    "us-gaap:PropertyPlantAndEquipmentNet",
    "us-gaap:Goodwill",
    "us-gaap:LongTermDebt",
    "us-gaap:LongTermDebtCurrent",
    "us-gaap:StockholdersEquity",
    "us-gaap:RetainedEarningsAccumulatedDeficit",

    "us-gaap:Revenues",
    "us-gaap:GrossProfit",
    "us-gaap:OperatingIncomeLoss",
    "us-gaap:NetIncomeLoss",
    "us-gaap:InterestExpense",
    "us-gaap:SellingGeneralAndAdministrativeExpense",
    "us-gaap:ResearchAndDevelopmentExpense",

    "us-gaap:NetCashProvidedByUsedInOperatingActivities",
    "us-gaap:PaymentsToAcquirePropertyPlantAndEquipment"
]